// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: notification/pb/notification.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification related messages
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Priority      string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      string                 `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_pb_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Notification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notification) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Priority      string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Metadata      string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNotificationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNotificationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNotificationRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateNotificationRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNotificationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationsResponse) Reset() {
	*x = NotificationsResponse{}
	mi := &file_notification_pb_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationsResponse) ProtoMessage() {}

func (x *NotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationsResponse.ProtoReflect.Descriptor instead.
func (*NotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type NotificationStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationStatusRequest) Reset() {
	*x = NotificationStatusRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationStatusRequest) ProtoMessage() {}

func (x *NotificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationStatusRequest.ProtoReflect.Descriptor instead.
func (*NotificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NotificationStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_notification_pb_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Alert threshold related messages
type AlertThreshold struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	MetricType     string                 `protobuf:"bytes,5,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	ComparisonType string                 `protobuf:"bytes,6,opt,name=comparison_type,json=comparisonType,proto3" json:"comparison_type,omitempty"`
	Value          float64                `protobuf:"fixed64,7,opt,name=value,proto3" json:"value,omitempty"`
	Percentage     bool                   `protobuf:"varint,8,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Period         string                 `protobuf:"bytes,9,opt,name=period,proto3" json:"period,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AlertThreshold) Reset() {
	*x = AlertThreshold{}
	mi := &file_notification_pb_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertThreshold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertThreshold) ProtoMessage() {}

func (x *AlertThreshold) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertThreshold.ProtoReflect.Descriptor instead.
func (*AlertThreshold) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{6}
}

func (x *AlertThreshold) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertThreshold) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AlertThreshold) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AlertThreshold) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertThreshold) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *AlertThreshold) GetComparisonType() string {
	if x != nil {
		return x.ComparisonType
	}
	return ""
}

func (x *AlertThreshold) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AlertThreshold) GetPercentage() bool {
	if x != nil {
		return x.Percentage
	}
	return false
}

func (x *AlertThreshold) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *AlertThreshold) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlertThreshold) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AlertThreshold) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAlertThresholdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MetricType     string                 `protobuf:"bytes,4,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	ComparisonType string                 `protobuf:"bytes,5,opt,name=comparison_type,json=comparisonType,proto3" json:"comparison_type,omitempty"`
	Value          float64                `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	Percentage     bool                   `protobuf:"varint,7,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Period         string                 `protobuf:"bytes,8,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAlertThresholdRequest) Reset() {
	*x = CreateAlertThresholdRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertThresholdRequest) ProtoMessage() {}

func (x *CreateAlertThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertThresholdRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertThresholdRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAlertThresholdRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateAlertThresholdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAlertThresholdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlertThresholdRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *CreateAlertThresholdRequest) GetComparisonType() string {
	if x != nil {
		return x.ComparisonType
	}
	return ""
}

func (x *CreateAlertThresholdRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateAlertThresholdRequest) GetPercentage() bool {
	if x != nil {
		return x.Percentage
	}
	return false
}

func (x *CreateAlertThresholdRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetAlertThresholdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	MetricType    string                 `protobuf:"bytes,2,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertThresholdsRequest) Reset() {
	*x = GetAlertThresholdsRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertThresholdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertThresholdsRequest) ProtoMessage() {}

func (x *GetAlertThresholdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertThresholdsRequest.ProtoReflect.Descriptor instead.
func (*GetAlertThresholdsRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{8}
}

func (x *GetAlertThresholdsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetAlertThresholdsRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

type AlertThresholdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thresholds    []*AlertThreshold      `protobuf:"bytes,1,rep,name=thresholds,proto3" json:"thresholds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertThresholdsResponse) Reset() {
	*x = AlertThresholdsResponse{}
	mi := &file_notification_pb_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertThresholdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertThresholdsResponse) ProtoMessage() {}

func (x *AlertThresholdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertThresholdsResponse.ProtoReflect.Descriptor instead.
func (*AlertThresholdsResponse) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{9}
}

func (x *AlertThresholdsResponse) GetThresholds() []*AlertThreshold {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

type UpdateAlertThresholdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThresholdId    string                 `protobuf:"bytes,1,opt,name=threshold_id,json=thresholdId,proto3" json:"threshold_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	MetricType     string                 `protobuf:"bytes,5,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	ComparisonType string                 `protobuf:"bytes,6,opt,name=comparison_type,json=comparisonType,proto3" json:"comparison_type,omitempty"`
	Value          float64                `protobuf:"fixed64,7,opt,name=value,proto3" json:"value,omitempty"`
	Percentage     bool                   `protobuf:"varint,8,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Period         string                 `protobuf:"bytes,9,opt,name=period,proto3" json:"period,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAlertThresholdRequest) Reset() {
	*x = UpdateAlertThresholdRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertThresholdRequest) ProtoMessage() {}

func (x *UpdateAlertThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertThresholdRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertThresholdRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAlertThresholdRequest) GetThresholdId() string {
	if x != nil {
		return x.ThresholdId
	}
	return ""
}

func (x *UpdateAlertThresholdRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateAlertThresholdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateAlertThresholdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAlertThresholdRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *UpdateAlertThresholdRequest) GetComparisonType() string {
	if x != nil {
		return x.ComparisonType
	}
	return ""
}

func (x *UpdateAlertThresholdRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *UpdateAlertThresholdRequest) GetPercentage() bool {
	if x != nil {
		return x.Percentage
	}
	return false
}

func (x *UpdateAlertThresholdRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *UpdateAlertThresholdRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteAlertThresholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ThresholdId   string                 `protobuf:"bytes,2,opt,name=threshold_id,json=thresholdId,proto3" json:"threshold_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertThresholdRequest) Reset() {
	*x = DeleteAlertThresholdRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertThresholdRequest) ProtoMessage() {}

func (x *DeleteAlertThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertThresholdRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertThresholdRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAlertThresholdRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteAlertThresholdRequest) GetThresholdId() string {
	if x != nil {
		return x.ThresholdId
	}
	return ""
}

// Scheduled report related messages
type ScheduledReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ReportType     string                 `protobuf:"bytes,6,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	Schedule       string                 `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Filters        string                 `protobuf:"bytes,8,opt,name=filters,proto3" json:"filters,omitempty"`
	DeliveryType   string                 `protobuf:"bytes,9,opt,name=delivery_type,json=deliveryType,proto3" json:"delivery_type,omitempty"`
	EmailAddresses string                 `protobuf:"bytes,10,opt,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	Status         string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	LastRunAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	NextRunAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduledReport) Reset() {
	*x = ScheduledReport{}
	mi := &file_notification_pb_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledReport) ProtoMessage() {}

func (x *ScheduledReport) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledReport.ProtoReflect.Descriptor instead.
func (*ScheduledReport) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{12}
}

func (x *ScheduledReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduledReport) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScheduledReport) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScheduledReport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduledReport) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScheduledReport) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *ScheduledReport) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *ScheduledReport) GetFilters() string {
	if x != nil {
		return x.Filters
	}
	return ""
}

func (x *ScheduledReport) GetDeliveryType() string {
	if x != nil {
		return x.DeliveryType
	}
	return ""
}

func (x *ScheduledReport) GetEmailAddresses() string {
	if x != nil {
		return x.EmailAddresses
	}
	return ""
}

func (x *ScheduledReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScheduledReport) GetLastRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunAt
	}
	return nil
}

func (x *ScheduledReport) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *ScheduledReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScheduledReport) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateScheduledReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ReportType     string                 `protobuf:"bytes,5,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	Schedule       string                 `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Filters        string                 `protobuf:"bytes,7,opt,name=filters,proto3" json:"filters,omitempty"`
	DeliveryType   string                 `protobuf:"bytes,8,opt,name=delivery_type,json=deliveryType,proto3" json:"delivery_type,omitempty"`
	EmailAddresses string                 `protobuf:"bytes,9,opt,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateScheduledReportRequest) Reset() {
	*x = CreateScheduledReportRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduledReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledReportRequest) ProtoMessage() {}

func (x *CreateScheduledReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledReportRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduledReportRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{13}
}

func (x *CreateScheduledReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateScheduledReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateScheduledReportRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScheduledReportRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScheduledReportRequest) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *CreateScheduledReportRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CreateScheduledReportRequest) GetFilters() string {
	if x != nil {
		return x.Filters
	}
	return ""
}

func (x *CreateScheduledReportRequest) GetDeliveryType() string {
	if x != nil {
		return x.DeliveryType
	}
	return ""
}

func (x *CreateScheduledReportRequest) GetEmailAddresses() string {
	if x != nil {
		return x.EmailAddresses
	}
	return ""
}

type GetScheduledReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledReportsRequest) Reset() {
	*x = GetScheduledReportsRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledReportsRequest) ProtoMessage() {}

func (x *GetScheduledReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledReportsRequest.ProtoReflect.Descriptor instead.
func (*GetScheduledReportsRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{14}
}

func (x *GetScheduledReportsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ScheduledReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*ScheduledReport     `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledReportsResponse) Reset() {
	*x = ScheduledReportsResponse{}
	mi := &file_notification_pb_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledReportsResponse) ProtoMessage() {}

func (x *ScheduledReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledReportsResponse.ProtoReflect.Descriptor instead.
func (*ScheduledReportsResponse) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{15}
}

func (x *ScheduledReportsResponse) GetReports() []*ScheduledReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type UpdateScheduledReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReportId       string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ReportType     string                 `protobuf:"bytes,6,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	Schedule       string                 `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Filters        string                 `protobuf:"bytes,8,opt,name=filters,proto3" json:"filters,omitempty"`
	DeliveryType   string                 `protobuf:"bytes,9,opt,name=delivery_type,json=deliveryType,proto3" json:"delivery_type,omitempty"`
	EmailAddresses string                 `protobuf:"bytes,10,opt,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	Status         string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateScheduledReportRequest) Reset() {
	*x = UpdateScheduledReportRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduledReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduledReportRequest) ProtoMessage() {}

func (x *UpdateScheduledReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduledReportRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduledReportRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateScheduledReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetFilters() string {
	if x != nil {
		return x.Filters
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetDeliveryType() string {
	if x != nil {
		return x.DeliveryType
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetEmailAddresses() string {
	if x != nil {
		return x.EmailAddresses
	}
	return ""
}

func (x *UpdateScheduledReportRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteScheduledReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduledReportRequest) Reset() {
	*x = DeleteScheduledReportRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduledReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduledReportRequest) ProtoMessage() {}

func (x *DeleteScheduledReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduledReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduledReportRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteScheduledReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteScheduledReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

// Background process related messages
type CheckAlertThresholdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAlertThresholdsRequest) Reset() {
	*x = CheckAlertThresholdsRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAlertThresholdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAlertThresholdsRequest) ProtoMessage() {}

func (x *CheckAlertThresholdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAlertThresholdsRequest.ProtoReflect.Descriptor instead.
func (*CheckAlertThresholdsRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{18}
}

func (x *CheckAlertThresholdsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ProcessScheduledReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessScheduledReportsRequest) Reset() {
	*x = ProcessScheduledReportsRequest{}
	mi := &file_notification_pb_notification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessScheduledReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessScheduledReportsRequest) ProtoMessage() {}

func (x *ProcessScheduledReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_pb_notification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessScheduledReportsRequest.ProtoReflect.Descriptor instead.
func (*ProcessScheduledReportsRequest) Descriptor() ([]byte, []int) {
	return file_notification_pb_notification_proto_rawDescGZIP(), []int{19}
}

func (x *ProcessScheduledReportsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

var File_notification_pb_notification_proto protoreflect.FileDescriptor

const file_notification_pb_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/pb/notification.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1a\n" +
	"\bmetadata\x18\t \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcd\x01\n" +
	"\x19CreateNotificationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\"g\n" +
	"\x17GetNotificationsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"Y\n" +
	"\x15NotificationsResponse\x12@\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1a.notification.NotificationR\rnotifications\"a\n" +
	"\x19NotificationStatusRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\"J\n" +
	"\x14UpdateStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x03\n" +
	"\x0eAlertThreshold\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1f\n" +
	"\vmetric_type\x18\x05 \x01(\tR\n" +
	"metricType\x12'\n" +
	"\x0fcomparison_type\x18\x06 \x01(\tR\x0ecomparisonType\x12\x14\n" +
	"\x05value\x18\a \x01(\x01R\x05value\x12\x1e\n" +
	"\n" +
	"percentage\x18\b \x01(\bR\n" +
	"percentage\x12\x16\n" +
	"\x06period\x18\t \x01(\tR\x06period\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xff\x01\n" +
	"\x1bCreateAlertThresholdRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vmetric_type\x18\x04 \x01(\tR\n" +
	"metricType\x12'\n" +
	"\x0fcomparison_type\x18\x05 \x01(\tR\x0ecomparisonType\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x01R\x05value\x12\x1e\n" +
	"\n" +
	"percentage\x18\a \x01(\bR\n" +
	"percentage\x12\x16\n" +
	"\x06period\x18\b \x01(\tR\x06period\"Y\n" +
	"\x19GetAlertThresholdsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vmetric_type\x18\x02 \x01(\tR\n" +
	"metricType\"W\n" +
	"\x17AlertThresholdsResponse\x12<\n" +
	"\n" +
	"thresholds\x18\x01 \x03(\v2\x1c.notification.AlertThresholdR\n" +
	"thresholds\"\xba\x02\n" +
	"\x1bUpdateAlertThresholdRequest\x12!\n" +
	"\fthreshold_id\x18\x01 \x01(\tR\vthresholdId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1f\n" +
	"\vmetric_type\x18\x05 \x01(\tR\n" +
	"metricType\x12'\n" +
	"\x0fcomparison_type\x18\x06 \x01(\tR\x0ecomparisonType\x12\x14\n" +
	"\x05value\x18\a \x01(\x01R\x05value\x12\x1e\n" +
	"\n" +
	"percentage\x18\b \x01(\bR\n" +
	"percentage\x12\x16\n" +
	"\x06period\x18\t \x01(\tR\x06period\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"]\n" +
	"\x1bDeleteAlertThresholdRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fthreshold_id\x18\x02 \x01(\tR\vthresholdId\"\xb8\x04\n" +
	"\x0fScheduledReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1f\n" +
	"\vreport_type\x18\x06 \x01(\tR\n" +
	"reportType\x12\x1a\n" +
	"\bschedule\x18\a \x01(\tR\bschedule\x12\x18\n" +
	"\afilters\x18\b \x01(\tR\afilters\x12#\n" +
	"\rdelivery_type\x18\t \x01(\tR\fdeliveryType\x12'\n" +
	"\x0femail_addresses\x18\n" +
	" \x01(\tR\x0eemailAddresses\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12:\n" +
	"\vlast_run_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tlastRunAt\x12:\n" +
	"\vnext_run_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaf\x02\n" +
	"\x1cCreateScheduledReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vreport_type\x18\x05 \x01(\tR\n" +
	"reportType\x12\x1a\n" +
	"\bschedule\x18\x06 \x01(\tR\bschedule\x12\x18\n" +
	"\afilters\x18\a \x01(\tR\afilters\x12#\n" +
	"\rdelivery_type\x18\b \x01(\tR\fdeliveryType\x12'\n" +
	"\x0femail_addresses\x18\t \x01(\tR\x0eemailAddresses\"9\n" +
	"\x1aGetScheduledReportsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"S\n" +
	"\x18ScheduledReportsResponse\x127\n" +
	"\areports\x18\x01 \x03(\v2\x1d.notification.ScheduledReportR\areports\"\xe4\x02\n" +
	"\x1cUpdateScheduledReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1f\n" +
	"\vreport_type\x18\x06 \x01(\tR\n" +
	"reportType\x12\x1a\n" +
	"\bschedule\x18\a \x01(\tR\bschedule\x12\x18\n" +
	"\afilters\x18\b \x01(\tR\afilters\x12#\n" +
	"\rdelivery_type\x18\t \x01(\tR\fdeliveryType\x12'\n" +
	"\x0femail_addresses\x18\n" +
	" \x01(\tR\x0eemailAddresses\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\"X\n" +
	"\x1cDeleteScheduledReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\":\n" +
	"\x1bCheckAlertThresholdsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"=\n" +
	"\x1eProcessScheduledReportsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId2\xfd\v\n" +
	"\x13NotificationService\x12Y\n" +
	"\x12CreateNotification\x12'.notification.CreateNotificationRequest\x1a\x1a.notification.Notification\x12^\n" +
	"\x10GetNotifications\x12%.notification.GetNotificationsRequest\x1a#.notification.NotificationsResponse\x12e\n" +
	"\x16MarkNotificationAsRead\x12'.notification.NotificationStatusRequest\x1a\".notification.UpdateStatusResponse\x12b\n" +
	"\x13ArchiveNotification\x12'.notification.NotificationStatusRequest\x1a\".notification.UpdateStatusResponse\x12a\n" +
	"\x12DeleteNotification\x12'.notification.NotificationStatusRequest\x1a\".notification.UpdateStatusResponse\x12_\n" +
	"\x14CreateAlertThreshold\x12).notification.CreateAlertThresholdRequest\x1a\x1c.notification.AlertThreshold\x12d\n" +
	"\x12GetAlertThresholds\x12'.notification.GetAlertThresholdsRequest\x1a%.notification.AlertThresholdsResponse\x12_\n" +
	"\x14UpdateAlertThreshold\x12).notification.UpdateAlertThresholdRequest\x1a\x1c.notification.AlertThreshold\x12e\n" +
	"\x14DeleteAlertThreshold\x12).notification.DeleteAlertThresholdRequest\x1a\".notification.UpdateStatusResponse\x12b\n" +
	"\x15CreateScheduledReport\x12*.notification.CreateScheduledReportRequest\x1a\x1d.notification.ScheduledReport\x12g\n" +
	"\x13GetScheduledReports\x12(.notification.GetScheduledReportsRequest\x1a&.notification.ScheduledReportsResponse\x12b\n" +
	"\x15UpdateScheduledReport\x12*.notification.UpdateScheduledReportRequest\x1a\x1d.notification.ScheduledReport\x12g\n" +
	"\x15DeleteScheduledReport\x12*.notification.DeleteScheduledReportRequest\x1a\".notification.UpdateStatusResponse\x12f\n" +
	"\x14CheckAlertThresholds\x12).notification.CheckAlertThresholdsRequest\x1a#.notification.NotificationsResponse\x12l\n" +
	"\x17ProcessScheduledReports\x12,.notification.ProcessScheduledReportsRequest\x1a#.notification.NotificationsResponseB5Z3github.com/donaldnash/go-competitor/notification/pbb\x06proto3"

var (
	file_notification_pb_notification_proto_rawDescOnce sync.Once
	file_notification_pb_notification_proto_rawDescData []byte
)

func file_notification_pb_notification_proto_rawDescGZIP() []byte {
	file_notification_pb_notification_proto_rawDescOnce.Do(func() {
		file_notification_pb_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_pb_notification_proto_rawDesc), len(file_notification_pb_notification_proto_rawDesc)))
	})
	return file_notification_pb_notification_proto_rawDescData
}

var file_notification_pb_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_notification_pb_notification_proto_goTypes = []any{
	(*Notification)(nil),                   // 0: notification.Notification
	(*CreateNotificationRequest)(nil),      // 1: notification.CreateNotificationRequest
	(*GetNotificationsRequest)(nil),        // 2: notification.GetNotificationsRequest
	(*NotificationsResponse)(nil),          // 3: notification.NotificationsResponse
	(*NotificationStatusRequest)(nil),      // 4: notification.NotificationStatusRequest
	(*UpdateStatusResponse)(nil),           // 5: notification.UpdateStatusResponse
	(*AlertThreshold)(nil),                 // 6: notification.AlertThreshold
	(*CreateAlertThresholdRequest)(nil),    // 7: notification.CreateAlertThresholdRequest
	(*GetAlertThresholdsRequest)(nil),      // 8: notification.GetAlertThresholdsRequest
	(*AlertThresholdsResponse)(nil),        // 9: notification.AlertThresholdsResponse
	(*UpdateAlertThresholdRequest)(nil),    // 10: notification.UpdateAlertThresholdRequest
	(*DeleteAlertThresholdRequest)(nil),    // 11: notification.DeleteAlertThresholdRequest
	(*ScheduledReport)(nil),                // 12: notification.ScheduledReport
	(*CreateScheduledReportRequest)(nil),   // 13: notification.CreateScheduledReportRequest
	(*GetScheduledReportsRequest)(nil),     // 14: notification.GetScheduledReportsRequest
	(*ScheduledReportsResponse)(nil),       // 15: notification.ScheduledReportsResponse
	(*UpdateScheduledReportRequest)(nil),   // 16: notification.UpdateScheduledReportRequest
	(*DeleteScheduledReportRequest)(nil),   // 17: notification.DeleteScheduledReportRequest
	(*CheckAlertThresholdsRequest)(nil),    // 18: notification.CheckAlertThresholdsRequest
	(*ProcessScheduledReportsRequest)(nil), // 19: notification.ProcessScheduledReportsRequest
	(*timestamppb.Timestamp)(nil),          // 20: google.protobuf.Timestamp
}
var file_notification_pb_notification_proto_depIdxs = []int32{
	20, // 0: notification.Notification.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: notification.Notification.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: notification.NotificationsResponse.notifications:type_name -> notification.Notification
	20, // 3: notification.AlertThreshold.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: notification.AlertThreshold.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 5: notification.AlertThresholdsResponse.thresholds:type_name -> notification.AlertThreshold
	20, // 6: notification.ScheduledReport.last_run_at:type_name -> google.protobuf.Timestamp
	20, // 7: notification.ScheduledReport.next_run_at:type_name -> google.protobuf.Timestamp
	20, // 8: notification.ScheduledReport.created_at:type_name -> google.protobuf.Timestamp
	20, // 9: notification.ScheduledReport.updated_at:type_name -> google.protobuf.Timestamp
	12, // 10: notification.ScheduledReportsResponse.reports:type_name -> notification.ScheduledReport
	1,  // 11: notification.NotificationService.CreateNotification:input_type -> notification.CreateNotificationRequest
	2,  // 12: notification.NotificationService.GetNotifications:input_type -> notification.GetNotificationsRequest
	4,  // 13: notification.NotificationService.MarkNotificationAsRead:input_type -> notification.NotificationStatusRequest
	4,  // 14: notification.NotificationService.ArchiveNotification:input_type -> notification.NotificationStatusRequest
	4,  // 15: notification.NotificationService.DeleteNotification:input_type -> notification.NotificationStatusRequest
	7,  // 16: notification.NotificationService.CreateAlertThreshold:input_type -> notification.CreateAlertThresholdRequest
	8,  // 17: notification.NotificationService.GetAlertThresholds:input_type -> notification.GetAlertThresholdsRequest
	10, // 18: notification.NotificationService.UpdateAlertThreshold:input_type -> notification.UpdateAlertThresholdRequest
	11, // 19: notification.NotificationService.DeleteAlertThreshold:input_type -> notification.DeleteAlertThresholdRequest
	13, // 20: notification.NotificationService.CreateScheduledReport:input_type -> notification.CreateScheduledReportRequest
	14, // 21: notification.NotificationService.GetScheduledReports:input_type -> notification.GetScheduledReportsRequest
	16, // 22: notification.NotificationService.UpdateScheduledReport:input_type -> notification.UpdateScheduledReportRequest
	17, // 23: notification.NotificationService.DeleteScheduledReport:input_type -> notification.DeleteScheduledReportRequest
	18, // 24: notification.NotificationService.CheckAlertThresholds:input_type -> notification.CheckAlertThresholdsRequest
	19, // 25: notification.NotificationService.ProcessScheduledReports:input_type -> notification.ProcessScheduledReportsRequest
	0,  // 26: notification.NotificationService.CreateNotification:output_type -> notification.Notification
	3,  // 27: notification.NotificationService.GetNotifications:output_type -> notification.NotificationsResponse
	5,  // 28: notification.NotificationService.MarkNotificationAsRead:output_type -> notification.UpdateStatusResponse
	5,  // 29: notification.NotificationService.ArchiveNotification:output_type -> notification.UpdateStatusResponse
	5,  // 30: notification.NotificationService.DeleteNotification:output_type -> notification.UpdateStatusResponse
	6,  // 31: notification.NotificationService.CreateAlertThreshold:output_type -> notification.AlertThreshold
	9,  // 32: notification.NotificationService.GetAlertThresholds:output_type -> notification.AlertThresholdsResponse
	6,  // 33: notification.NotificationService.UpdateAlertThreshold:output_type -> notification.AlertThreshold
	5,  // 34: notification.NotificationService.DeleteAlertThreshold:output_type -> notification.UpdateStatusResponse
	12, // 35: notification.NotificationService.CreateScheduledReport:output_type -> notification.ScheduledReport
	15, // 36: notification.NotificationService.GetScheduledReports:output_type -> notification.ScheduledReportsResponse
	12, // 37: notification.NotificationService.UpdateScheduledReport:output_type -> notification.ScheduledReport
	5,  // 38: notification.NotificationService.DeleteScheduledReport:output_type -> notification.UpdateStatusResponse
	3,  // 39: notification.NotificationService.CheckAlertThresholds:output_type -> notification.NotificationsResponse
	3,  // 40: notification.NotificationService.ProcessScheduledReports:output_type -> notification.NotificationsResponse
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_notification_pb_notification_proto_init() }
func file_notification_pb_notification_proto_init() {
	if File_notification_pb_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_pb_notification_proto_rawDesc), len(file_notification_pb_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_pb_notification_proto_goTypes,
		DependencyIndexes: file_notification_pb_notification_proto_depIdxs,
		MessageInfos:      file_notification_pb_notification_proto_msgTypes,
	}.Build()
	File_notification_pb_notification_proto = out.File
	file_notification_pb_notification_proto_goTypes = nil
	file_notification_pb_notification_proto_depIdxs = nil
}
