// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: competitor/pb/competitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Competitor management
type AddCompetitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformId    string                 `protobuf:"bytes,4,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCompetitorRequest) Reset() {
	*x = AddCompetitorRequest{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCompetitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCompetitorRequest) ProtoMessage() {}

func (x *AddCompetitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCompetitorRequest.ProtoReflect.Descriptor instead.
func (*AddCompetitorRequest) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{0}
}

func (x *AddCompetitorRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AddCompetitorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCompetitorRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AddCompetitorRequest) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *AddCompetitorRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetCompetitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompetitorId  string                 `protobuf:"bytes,2,opt,name=competitor_id,json=competitorId,proto3" json:"competitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitorRequest) Reset() {
	*x = GetCompetitorRequest{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitorRequest) ProtoMessage() {}

func (x *GetCompetitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitorRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitorRequest) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{1}
}

func (x *GetCompetitorRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetCompetitorRequest) GetCompetitorId() string {
	if x != nil {
		return x.CompetitorId
	}
	return ""
}

type ListCompetitorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // Optional, filter by platform
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompetitorsRequest) Reset() {
	*x = ListCompetitorsRequest{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompetitorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompetitorsRequest) ProtoMessage() {}

func (x *ListCompetitorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompetitorsRequest.ProtoReflect.Descriptor instead.
func (*ListCompetitorsRequest) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{2}
}

func (x *ListCompetitorsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListCompetitorsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type ListCompetitorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Competitors   []*Competitor          `protobuf:"bytes,1,rep,name=competitors,proto3" json:"competitors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompetitorsResponse) Reset() {
	*x = ListCompetitorsResponse{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompetitorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompetitorsResponse) ProtoMessage() {}

func (x *ListCompetitorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompetitorsResponse.ProtoReflect.Descriptor instead.
func (*ListCompetitorsResponse) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{3}
}

func (x *ListCompetitorsResponse) GetCompetitors() []*Competitor {
	if x != nil {
		return x.Competitors
	}
	return nil
}

type UpdateCompetitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompetitorId  string                 `protobuf:"bytes,2,opt,name=competitor_id,json=competitorId,proto3" json:"competitor_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformId    string                 `protobuf:"bytes,5,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompetitorRequest) Reset() {
	*x = UpdateCompetitorRequest{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompetitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitorRequest) ProtoMessage() {}

func (x *UpdateCompetitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitorRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitorRequest) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCompetitorRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateCompetitorRequest) GetCompetitorId() string {
	if x != nil {
		return x.CompetitorId
	}
	return ""
}

func (x *UpdateCompetitorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCompetitorRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpdateCompetitorRequest) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *UpdateCompetitorRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteCompetitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompetitorId  string                 `protobuf:"bytes,2,opt,name=competitor_id,json=competitorId,proto3" json:"competitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCompetitorRequest) Reset() {
	*x = DeleteCompetitorRequest{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCompetitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCompetitorRequest) ProtoMessage() {}

func (x *DeleteCompetitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCompetitorRequest.ProtoReflect.Descriptor instead.
func (*DeleteCompetitorRequest) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCompetitorRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteCompetitorRequest) GetCompetitorId() string {
	if x != nil {
		return x.CompetitorId
	}
	return ""
}

// Competitor metrics
type GetCompetitorMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompetitorId  string                 `protobuf:"bytes,2,opt,name=competitor_id,json=competitorId,proto3" json:"competitor_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitorMetricsRequest) Reset() {
	*x = GetCompetitorMetricsRequest{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitorMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitorMetricsRequest) ProtoMessage() {}

func (x *GetCompetitorMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitorMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetCompetitorMetricsRequest) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{6}
}

func (x *GetCompetitorMetricsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetCompetitorMetricsRequest) GetCompetitorId() string {
	if x != nil {
		return x.CompetitorId
	}
	return ""
}

func (x *GetCompetitorMetricsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetCompetitorMetricsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetCompetitorMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*CompetitorMetric    `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompetitorMetricsResponse) Reset() {
	*x = GetCompetitorMetricsResponse{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompetitorMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompetitorMetricsResponse) ProtoMessage() {}

func (x *GetCompetitorMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompetitorMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetCompetitorMetricsResponse) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{7}
}

func (x *GetCompetitorMetricsResponse) GetMetrics() []*CompetitorMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type CompareMetricsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompetitorId    string                 `protobuf:"bytes,2,opt,name=competitor_id,json=competitorId,proto3" json:"competitor_id,omitempty"`
	StartDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	LockedVariables *LockedVariables       `protobuf:"bytes,5,opt,name=locked_variables,json=lockedVariables,proto3" json:"locked_variables,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompareMetricsRequest) Reset() {
	*x = CompareMetricsRequest{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareMetricsRequest) ProtoMessage() {}

func (x *CompareMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareMetricsRequest.ProtoReflect.Descriptor instead.
func (*CompareMetricsRequest) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{8}
}

func (x *CompareMetricsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CompareMetricsRequest) GetCompetitorId() string {
	if x != nil {
		return x.CompetitorId
	}
	return ""
}

func (x *CompareMetricsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CompareMetricsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *CompareMetricsRequest) GetLockedVariables() *LockedVariables {
	if x != nil {
		return x.LockedVariables
	}
	return nil
}

type LockedVariables struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DayOfWeek       string                 `protobuf:"bytes,1,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`                 // Optional
	TimeGap         string                 `protobuf:"bytes,2,opt,name=time_gap,json=timeGap,proto3" json:"time_gap,omitempty"`                         // Optional
	ContentCategory string                 `protobuf:"bytes,3,opt,name=content_category,json=contentCategory,proto3" json:"content_category,omitempty"` // Optional
	ContentFormat   string                 `protobuf:"bytes,4,opt,name=content_format,json=contentFormat,proto3" json:"content_format,omitempty"`       // Optional
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LockedVariables) Reset() {
	*x = LockedVariables{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockedVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockedVariables) ProtoMessage() {}

func (x *LockedVariables) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockedVariables.ProtoReflect.Descriptor instead.
func (*LockedVariables) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{9}
}

func (x *LockedVariables) GetDayOfWeek() string {
	if x != nil {
		return x.DayOfWeek
	}
	return ""
}

func (x *LockedVariables) GetTimeGap() string {
	if x != nil {
		return x.TimeGap
	}
	return ""
}

func (x *LockedVariables) GetContentCategory() string {
	if x != nil {
		return x.ContentCategory
	}
	return ""
}

func (x *LockedVariables) GetContentFormat() string {
	if x != nil {
		return x.ContentFormat
	}
	return ""
}

type CompareMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Competitor    *CompetitorComparison  `protobuf:"bytes,1,opt,name=competitor,proto3" json:"competitor,omitempty"`
	Personal      *PersonalComparison    `protobuf:"bytes,2,opt,name=personal,proto3" json:"personal,omitempty"`
	Ratios        *ComparisonRatios      `protobuf:"bytes,3,opt,name=ratios,proto3" json:"ratios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareMetricsResponse) Reset() {
	*x = CompareMetricsResponse{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareMetricsResponse) ProtoMessage() {}

func (x *CompareMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareMetricsResponse.ProtoReflect.Descriptor instead.
func (*CompareMetricsResponse) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{10}
}

func (x *CompareMetricsResponse) GetCompetitor() *CompetitorComparison {
	if x != nil {
		return x.Competitor
	}
	return nil
}

func (x *CompareMetricsResponse) GetPersonal() *PersonalComparison {
	if x != nil {
		return x.Personal
	}
	return nil
}

func (x *CompareMetricsResponse) GetRatios() *ComparisonRatios {
	if x != nil {
		return x.Ratios
	}
	return nil
}

type CompetitorComparison struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*CompetitorMetric    `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Aggregates    *MetricAggregates      `protobuf:"bytes,2,opt,name=aggregates,proto3" json:"aggregates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitorComparison) Reset() {
	*x = CompetitorComparison{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitorComparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitorComparison) ProtoMessage() {}

func (x *CompetitorComparison) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitorComparison.ProtoReflect.Descriptor instead.
func (*CompetitorComparison) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{11}
}

func (x *CompetitorComparison) GetMetrics() []*CompetitorMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *CompetitorComparison) GetAggregates() *MetricAggregates {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

type PersonalComparison struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*PersonalMetric      `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Aggregates    *MetricAggregates      `protobuf:"bytes,2,opt,name=aggregates,proto3" json:"aggregates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalComparison) Reset() {
	*x = PersonalComparison{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalComparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalComparison) ProtoMessage() {}

func (x *PersonalComparison) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalComparison.ProtoReflect.Descriptor instead.
func (*PersonalComparison) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{12}
}

func (x *PersonalComparison) GetMetrics() []*PersonalMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *PersonalComparison) GetAggregates() *MetricAggregates {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

type MetricAggregates struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalLikes        int32                  `protobuf:"varint,1,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	TotalShares       int32                  `protobuf:"varint,2,opt,name=total_shares,json=totalShares,proto3" json:"total_shares,omitempty"`
	TotalComments     int32                  `protobuf:"varint,3,opt,name=total_comments,json=totalComments,proto3" json:"total_comments,omitempty"`
	AvgEngagementRate float64                `protobuf:"fixed64,4,opt,name=avg_engagement_rate,json=avgEngagementRate,proto3" json:"avg_engagement_rate,omitempty"`
	AvgWatchTime      float64                `protobuf:"fixed64,5,opt,name=avg_watch_time,json=avgWatchTime,proto3" json:"avg_watch_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricAggregates) Reset() {
	*x = MetricAggregates{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricAggregates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricAggregates) ProtoMessage() {}

func (x *MetricAggregates) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricAggregates.ProtoReflect.Descriptor instead.
func (*MetricAggregates) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{13}
}

func (x *MetricAggregates) GetTotalLikes() int32 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

func (x *MetricAggregates) GetTotalShares() int32 {
	if x != nil {
		return x.TotalShares
	}
	return 0
}

func (x *MetricAggregates) GetTotalComments() int32 {
	if x != nil {
		return x.TotalComments
	}
	return 0
}

func (x *MetricAggregates) GetAvgEngagementRate() float64 {
	if x != nil {
		return x.AvgEngagementRate
	}
	return 0
}

func (x *MetricAggregates) GetAvgWatchTime() float64 {
	if x != nil {
		return x.AvgWatchTime
	}
	return 0
}

type ComparisonRatios struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LikesRatio          float64                `protobuf:"fixed64,1,opt,name=likes_ratio,json=likesRatio,proto3" json:"likes_ratio,omitempty"`
	SharesRatio         float64                `protobuf:"fixed64,2,opt,name=shares_ratio,json=sharesRatio,proto3" json:"shares_ratio,omitempty"`
	CommentsRatio       float64                `protobuf:"fixed64,3,opt,name=comments_ratio,json=commentsRatio,proto3" json:"comments_ratio,omitempty"`
	EngagementRateRatio float64                `protobuf:"fixed64,4,opt,name=engagement_rate_ratio,json=engagementRateRatio,proto3" json:"engagement_rate_ratio,omitempty"`
	WatchTimeRatio      float64                `protobuf:"fixed64,5,opt,name=watch_time_ratio,json=watchTimeRatio,proto3" json:"watch_time_ratio,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ComparisonRatios) Reset() {
	*x = ComparisonRatios{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComparisonRatios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComparisonRatios) ProtoMessage() {}

func (x *ComparisonRatios) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComparisonRatios.ProtoReflect.Descriptor instead.
func (*ComparisonRatios) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{14}
}

func (x *ComparisonRatios) GetLikesRatio() float64 {
	if x != nil {
		return x.LikesRatio
	}
	return 0
}

func (x *ComparisonRatios) GetSharesRatio() float64 {
	if x != nil {
		return x.SharesRatio
	}
	return 0
}

func (x *ComparisonRatios) GetCommentsRatio() float64 {
	if x != nil {
		return x.CommentsRatio
	}
	return 0
}

func (x *ComparisonRatios) GetEngagementRateRatio() float64 {
	if x != nil {
		return x.EngagementRateRatio
	}
	return 0
}

func (x *ComparisonRatios) GetWatchTimeRatio() float64 {
	if x != nil {
		return x.WatchTimeRatio
	}
	return 0
}

type TrackCompetitorPostRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompetitorId     string                 `protobuf:"bytes,2,opt,name=competitor_id,json=competitorId,proto3" json:"competitor_id,omitempty"`
	PostId           string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Likes            int32                  `protobuf:"varint,4,opt,name=likes,proto3" json:"likes,omitempty"`
	Shares           int32                  `protobuf:"varint,5,opt,name=shares,proto3" json:"shares,omitempty"`
	Comments         int32                  `protobuf:"varint,6,opt,name=comments,proto3" json:"comments,omitempty"`
	ClickThroughRate float64                `protobuf:"fixed64,7,opt,name=click_through_rate,json=clickThroughRate,proto3" json:"click_through_rate,omitempty"`
	AvgWatchTime     float64                `protobuf:"fixed64,8,opt,name=avg_watch_time,json=avgWatchTime,proto3" json:"avg_watch_time,omitempty"`
	PostedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	EngagementRate   float64                `protobuf:"fixed64,10,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackCompetitorPostRequest) Reset() {
	*x = TrackCompetitorPostRequest{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackCompetitorPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackCompetitorPostRequest) ProtoMessage() {}

func (x *TrackCompetitorPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackCompetitorPostRequest.ProtoReflect.Descriptor instead.
func (*TrackCompetitorPostRequest) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{15}
}

func (x *TrackCompetitorPostRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TrackCompetitorPostRequest) GetCompetitorId() string {
	if x != nil {
		return x.CompetitorId
	}
	return ""
}

func (x *TrackCompetitorPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *TrackCompetitorPostRequest) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *TrackCompetitorPostRequest) GetShares() int32 {
	if x != nil {
		return x.Shares
	}
	return 0
}

func (x *TrackCompetitorPostRequest) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *TrackCompetitorPostRequest) GetClickThroughRate() float64 {
	if x != nil {
		return x.ClickThroughRate
	}
	return 0
}

func (x *TrackCompetitorPostRequest) GetAvgWatchTime() float64 {
	if x != nil {
		return x.AvgWatchTime
	}
	return 0
}

func (x *TrackCompetitorPostRequest) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *TrackCompetitorPostRequest) GetEngagementRate() float64 {
	if x != nil {
		return x.EngagementRate
	}
	return 0
}

// Models
type Competitor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformId    string                 `protobuf:"bytes,5,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Competitor) Reset() {
	*x = Competitor{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Competitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Competitor) ProtoMessage() {}

func (x *Competitor) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Competitor.ProtoReflect.Descriptor instead.
func (*Competitor) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{16}
}

func (x *Competitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Competitor) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Competitor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Competitor) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Competitor) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *Competitor) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Competitor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Competitor) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CompetitorMetric struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompetitorId     string                 `protobuf:"bytes,2,opt,name=competitor_id,json=competitorId,proto3" json:"competitor_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PostId           string                 `protobuf:"bytes,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Likes            int32                  `protobuf:"varint,5,opt,name=likes,proto3" json:"likes,omitempty"`
	Shares           int32                  `protobuf:"varint,6,opt,name=shares,proto3" json:"shares,omitempty"`
	Comments         int32                  `protobuf:"varint,7,opt,name=comments,proto3" json:"comments,omitempty"`
	ClickThroughRate float64                `protobuf:"fixed64,8,opt,name=click_through_rate,json=clickThroughRate,proto3" json:"click_through_rate,omitempty"`
	AvgWatchTime     float64                `protobuf:"fixed64,9,opt,name=avg_watch_time,json=avgWatchTime,proto3" json:"avg_watch_time,omitempty"`
	EngagementRate   float64                `protobuf:"fixed64,10,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"`
	PostedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompetitorMetric) Reset() {
	*x = CompetitorMetric{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitorMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitorMetric) ProtoMessage() {}

func (x *CompetitorMetric) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitorMetric.ProtoReflect.Descriptor instead.
func (*CompetitorMetric) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{17}
}

func (x *CompetitorMetric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompetitorMetric) GetCompetitorId() string {
	if x != nil {
		return x.CompetitorId
	}
	return ""
}

func (x *CompetitorMetric) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CompetitorMetric) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CompetitorMetric) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *CompetitorMetric) GetShares() int32 {
	if x != nil {
		return x.Shares
	}
	return 0
}

func (x *CompetitorMetric) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *CompetitorMetric) GetClickThroughRate() float64 {
	if x != nil {
		return x.ClickThroughRate
	}
	return 0
}

func (x *CompetitorMetric) GetAvgWatchTime() float64 {
	if x != nil {
		return x.AvgWatchTime
	}
	return 0
}

func (x *CompetitorMetric) GetEngagementRate() float64 {
	if x != nil {
		return x.EngagementRate
	}
	return 0
}

func (x *CompetitorMetric) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *CompetitorMetric) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PersonalMetric struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PostId           string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Likes            int32                  `protobuf:"varint,4,opt,name=likes,proto3" json:"likes,omitempty"`
	Shares           int32                  `protobuf:"varint,5,opt,name=shares,proto3" json:"shares,omitempty"`
	Comments         int32                  `protobuf:"varint,6,opt,name=comments,proto3" json:"comments,omitempty"`
	ClickThroughRate float64                `protobuf:"fixed64,7,opt,name=click_through_rate,json=clickThroughRate,proto3" json:"click_through_rate,omitempty"`
	AvgWatchTime     float64                `protobuf:"fixed64,8,opt,name=avg_watch_time,json=avgWatchTime,proto3" json:"avg_watch_time,omitempty"`
	EngagementRate   float64                `protobuf:"fixed64,9,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"`
	PostedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PersonalMetric) Reset() {
	*x = PersonalMetric{}
	mi := &file_competitor_pb_competitor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalMetric) ProtoMessage() {}

func (x *PersonalMetric) ProtoReflect() protoreflect.Message {
	mi := &file_competitor_pb_competitor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalMetric.ProtoReflect.Descriptor instead.
func (*PersonalMetric) Descriptor() ([]byte, []int) {
	return file_competitor_pb_competitor_proto_rawDescGZIP(), []int{18}
}

func (x *PersonalMetric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersonalMetric) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PersonalMetric) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PersonalMetric) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *PersonalMetric) GetShares() int32 {
	if x != nil {
		return x.Shares
	}
	return 0
}

func (x *PersonalMetric) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *PersonalMetric) GetClickThroughRate() float64 {
	if x != nil {
		return x.ClickThroughRate
	}
	return 0
}

func (x *PersonalMetric) GetAvgWatchTime() float64 {
	if x != nil {
		return x.AvgWatchTime
	}
	return 0
}

func (x *PersonalMetric) GetEngagementRate() float64 {
	if x != nil {
		return x.EngagementRate
	}
	return 0
}

func (x *PersonalMetric) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *PersonalMetric) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_competitor_pb_competitor_proto protoreflect.FileDescriptor

const file_competitor_pb_competitor_proto_rawDesc = "" +
	"\n" +
	"\x1ecompetitor/pb/competitor.proto\x12\n" +
	"competitor\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8d\x02\n" +
	"\x14AddCompetitorRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1f\n" +
	"\vplatform_id\x18\x04 \x01(\tR\n" +
	"platformId\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..competitor.AddCompetitorRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x14GetCompetitorRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rcompetitor_id\x18\x02 \x01(\tR\fcompetitorId\"Q\n" +
	"\x16ListCompetitorsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"S\n" +
	"\x17ListCompetitorsResponse\x128\n" +
	"\vcompetitors\x18\x01 \x03(\v2\x16.competitor.CompetitorR\vcompetitors\"\xb8\x02\n" +
	"\x17UpdateCompetitorRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rcompetitor_id\x18\x02 \x01(\tR\fcompetitorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1f\n" +
	"\vplatform_id\x18\x05 \x01(\tR\n" +
	"platformId\x12M\n" +
	"\bmetadata\x18\x06 \x03(\v21.competitor.UpdateCompetitorRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x17DeleteCompetitorRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rcompetitor_id\x18\x02 \x01(\tR\fcompetitorId\"\xd1\x01\n" +
	"\x1bGetCompetitorMetricsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rcompetitor_id\x18\x02 \x01(\tR\fcompetitorId\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"V\n" +
	"\x1cGetCompetitorMetricsResponse\x126\n" +
	"\ametrics\x18\x01 \x03(\v2\x1c.competitor.CompetitorMetricR\ametrics\"\x93\x02\n" +
	"\x15CompareMetricsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rcompetitor_id\x18\x02 \x01(\tR\fcompetitorId\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12F\n" +
	"\x10locked_variables\x18\x05 \x01(\v2\x1b.competitor.LockedVariablesR\x0flockedVariables\"\x9e\x01\n" +
	"\x0fLockedVariables\x12\x1e\n" +
	"\vday_of_week\x18\x01 \x01(\tR\tdayOfWeek\x12\x19\n" +
	"\btime_gap\x18\x02 \x01(\tR\atimeGap\x12)\n" +
	"\x10content_category\x18\x03 \x01(\tR\x0fcontentCategory\x12%\n" +
	"\x0econtent_format\x18\x04 \x01(\tR\rcontentFormat\"\xcc\x01\n" +
	"\x16CompareMetricsResponse\x12@\n" +
	"\n" +
	"competitor\x18\x01 \x01(\v2 .competitor.CompetitorComparisonR\n" +
	"competitor\x12:\n" +
	"\bpersonal\x18\x02 \x01(\v2\x1e.competitor.PersonalComparisonR\bpersonal\x124\n" +
	"\x06ratios\x18\x03 \x01(\v2\x1c.competitor.ComparisonRatiosR\x06ratios\"\x8c\x01\n" +
	"\x14CompetitorComparison\x126\n" +
	"\ametrics\x18\x01 \x03(\v2\x1c.competitor.CompetitorMetricR\ametrics\x12<\n" +
	"\n" +
	"aggregates\x18\x02 \x01(\v2\x1c.competitor.MetricAggregatesR\n" +
	"aggregates\"\x88\x01\n" +
	"\x12PersonalComparison\x124\n" +
	"\ametrics\x18\x01 \x03(\v2\x1a.competitor.PersonalMetricR\ametrics\x12<\n" +
	"\n" +
	"aggregates\x18\x02 \x01(\v2\x1c.competitor.MetricAggregatesR\n" +
	"aggregates\"\xd3\x01\n" +
	"\x10MetricAggregates\x12\x1f\n" +
	"\vtotal_likes\x18\x01 \x01(\x05R\n" +
	"totalLikes\x12!\n" +
	"\ftotal_shares\x18\x02 \x01(\x05R\vtotalShares\x12%\n" +
	"\x0etotal_comments\x18\x03 \x01(\x05R\rtotalComments\x12.\n" +
	"\x13avg_engagement_rate\x18\x04 \x01(\x01R\x11avgEngagementRate\x12$\n" +
	"\x0eavg_watch_time\x18\x05 \x01(\x01R\favgWatchTime\"\xdb\x01\n" +
	"\x10ComparisonRatios\x12\x1f\n" +
	"\vlikes_ratio\x18\x01 \x01(\x01R\n" +
	"likesRatio\x12!\n" +
	"\fshares_ratio\x18\x02 \x01(\x01R\vsharesRatio\x12%\n" +
	"\x0ecomments_ratio\x18\x03 \x01(\x01R\rcommentsRatio\x122\n" +
	"\x15engagement_rate_ratio\x18\x04 \x01(\x01R\x13engagementRateRatio\x12(\n" +
	"\x10watch_time_ratio\x18\x05 \x01(\x01R\x0ewatchTimeRatio\"\xf7\x02\n" +
	"\x1aTrackCompetitorPostRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rcompetitor_id\x18\x02 \x01(\tR\fcompetitorId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x12\x14\n" +
	"\x05likes\x18\x04 \x01(\x05R\x05likes\x12\x16\n" +
	"\x06shares\x18\x05 \x01(\x05R\x06shares\x12\x1a\n" +
	"\bcomments\x18\x06 \x01(\x05R\bcomments\x12,\n" +
	"\x12click_through_rate\x18\a \x01(\x01R\x10clickThroughRate\x12$\n" +
	"\x0eavg_watch_time\x18\b \x01(\x01R\favgWatchTime\x127\n" +
	"\tposted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x12'\n" +
	"\x0fengagement_rate\x18\n" +
	" \x01(\x01R\x0eengagementRate\"\xff\x02\n" +
	"\n" +
	"Competitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1f\n" +
	"\vplatform_id\x18\x05 \x01(\tR\n" +
	"platformId\x12@\n" +
	"\bmetadata\x18\x06 \x03(\v2$.competitor.Competitor.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x03\n" +
	"\x10CompetitorMetric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcompetitor_id\x18\x02 \x01(\tR\fcompetitorId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\apost_id\x18\x04 \x01(\tR\x06postId\x12\x14\n" +
	"\x05likes\x18\x05 \x01(\x05R\x05likes\x12\x16\n" +
	"\x06shares\x18\x06 \x01(\x05R\x06shares\x12\x1a\n" +
	"\bcomments\x18\a \x01(\x05R\bcomments\x12,\n" +
	"\x12click_through_rate\x18\b \x01(\x01R\x10clickThroughRate\x12$\n" +
	"\x0eavg_watch_time\x18\t \x01(\x01R\favgWatchTime\x12'\n" +
	"\x0fengagement_rate\x18\n" +
	" \x01(\x01R\x0eengagementRate\x127\n" +
	"\tposted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x91\x03\n" +
	"\x0ePersonalMetric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x12\x14\n" +
	"\x05likes\x18\x04 \x01(\x05R\x05likes\x12\x16\n" +
	"\x06shares\x18\x05 \x01(\x05R\x06shares\x12\x1a\n" +
	"\bcomments\x18\x06 \x01(\x05R\bcomments\x12,\n" +
	"\x12click_through_rate\x18\a \x01(\x01R\x10clickThroughRate\x12$\n" +
	"\x0eavg_watch_time\x18\b \x01(\x01R\favgWatchTime\x12'\n" +
	"\x0fengagement_rate\x18\t \x01(\x01R\x0eengagementRate\x127\n" +
	"\tposted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xd8\x05\n" +
	"\x11CompetitorService\x12K\n" +
	"\rAddCompetitor\x12 .competitor.AddCompetitorRequest\x1a\x16.competitor.Competitor\"\x00\x12K\n" +
	"\rGetCompetitor\x12 .competitor.GetCompetitorRequest\x1a\x16.competitor.Competitor\"\x00\x12\\\n" +
	"\x0fListCompetitors\x12\".competitor.ListCompetitorsRequest\x1a#.competitor.ListCompetitorsResponse\"\x00\x12Q\n" +
	"\x10UpdateCompetitor\x12#.competitor.UpdateCompetitorRequest\x1a\x16.competitor.Competitor\"\x00\x12Q\n" +
	"\x10DeleteCompetitor\x12#.competitor.DeleteCompetitorRequest\x1a\x16.google.protobuf.Empty\"\x00\x12k\n" +
	"\x14GetCompetitorMetrics\x12'.competitor.GetCompetitorMetricsRequest\x1a(.competitor.GetCompetitorMetricsResponse\"\x00\x12Y\n" +
	"\x0eCompareMetrics\x12!.competitor.CompareMetricsRequest\x1a\".competitor.CompareMetricsResponse\"\x00\x12]\n" +
	"\x13TrackCompetitorPost\x12&.competitor.TrackCompetitorPostRequest\x1a\x1c.competitor.CompetitorMetric\"\x00B3Z1github.com/donaldnash/go-competitor/competitor/pbb\x06proto3"

var (
	file_competitor_pb_competitor_proto_rawDescOnce sync.Once
	file_competitor_pb_competitor_proto_rawDescData []byte
)

func file_competitor_pb_competitor_proto_rawDescGZIP() []byte {
	file_competitor_pb_competitor_proto_rawDescOnce.Do(func() {
		file_competitor_pb_competitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_competitor_pb_competitor_proto_rawDesc), len(file_competitor_pb_competitor_proto_rawDesc)))
	})
	return file_competitor_pb_competitor_proto_rawDescData
}

var file_competitor_pb_competitor_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_competitor_pb_competitor_proto_goTypes = []any{
	(*AddCompetitorRequest)(nil),         // 0: competitor.AddCompetitorRequest
	(*GetCompetitorRequest)(nil),         // 1: competitor.GetCompetitorRequest
	(*ListCompetitorsRequest)(nil),       // 2: competitor.ListCompetitorsRequest
	(*ListCompetitorsResponse)(nil),      // 3: competitor.ListCompetitorsResponse
	(*UpdateCompetitorRequest)(nil),      // 4: competitor.UpdateCompetitorRequest
	(*DeleteCompetitorRequest)(nil),      // 5: competitor.DeleteCompetitorRequest
	(*GetCompetitorMetricsRequest)(nil),  // 6: competitor.GetCompetitorMetricsRequest
	(*GetCompetitorMetricsResponse)(nil), // 7: competitor.GetCompetitorMetricsResponse
	(*CompareMetricsRequest)(nil),        // 8: competitor.CompareMetricsRequest
	(*LockedVariables)(nil),              // 9: competitor.LockedVariables
	(*CompareMetricsResponse)(nil),       // 10: competitor.CompareMetricsResponse
	(*CompetitorComparison)(nil),         // 11: competitor.CompetitorComparison
	(*PersonalComparison)(nil),           // 12: competitor.PersonalComparison
	(*MetricAggregates)(nil),             // 13: competitor.MetricAggregates
	(*ComparisonRatios)(nil),             // 14: competitor.ComparisonRatios
	(*TrackCompetitorPostRequest)(nil),   // 15: competitor.TrackCompetitorPostRequest
	(*Competitor)(nil),                   // 16: competitor.Competitor
	(*CompetitorMetric)(nil),             // 17: competitor.CompetitorMetric
	(*PersonalMetric)(nil),               // 18: competitor.PersonalMetric
	nil,                                  // 19: competitor.AddCompetitorRequest.MetadataEntry
	nil,                                  // 20: competitor.UpdateCompetitorRequest.MetadataEntry
	nil,                                  // 21: competitor.Competitor.MetadataEntry
	(*timestamppb.Timestamp)(nil),        // 22: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 23: google.protobuf.Empty
}
var file_competitor_pb_competitor_proto_depIdxs = []int32{
	19, // 0: competitor.AddCompetitorRequest.metadata:type_name -> competitor.AddCompetitorRequest.MetadataEntry
	16, // 1: competitor.ListCompetitorsResponse.competitors:type_name -> competitor.Competitor
	20, // 2: competitor.UpdateCompetitorRequest.metadata:type_name -> competitor.UpdateCompetitorRequest.MetadataEntry
	22, // 3: competitor.GetCompetitorMetricsRequest.start_date:type_name -> google.protobuf.Timestamp
	22, // 4: competitor.GetCompetitorMetricsRequest.end_date:type_name -> google.protobuf.Timestamp
	17, // 5: competitor.GetCompetitorMetricsResponse.metrics:type_name -> competitor.CompetitorMetric
	22, // 6: competitor.CompareMetricsRequest.start_date:type_name -> google.protobuf.Timestamp
	22, // 7: competitor.CompareMetricsRequest.end_date:type_name -> google.protobuf.Timestamp
	9,  // 8: competitor.CompareMetricsRequest.locked_variables:type_name -> competitor.LockedVariables
	11, // 9: competitor.CompareMetricsResponse.competitor:type_name -> competitor.CompetitorComparison
	12, // 10: competitor.CompareMetricsResponse.personal:type_name -> competitor.PersonalComparison
	14, // 11: competitor.CompareMetricsResponse.ratios:type_name -> competitor.ComparisonRatios
	17, // 12: competitor.CompetitorComparison.metrics:type_name -> competitor.CompetitorMetric
	13, // 13: competitor.CompetitorComparison.aggregates:type_name -> competitor.MetricAggregates
	18, // 14: competitor.PersonalComparison.metrics:type_name -> competitor.PersonalMetric
	13, // 15: competitor.PersonalComparison.aggregates:type_name -> competitor.MetricAggregates
	22, // 16: competitor.TrackCompetitorPostRequest.posted_at:type_name -> google.protobuf.Timestamp
	21, // 17: competitor.Competitor.metadata:type_name -> competitor.Competitor.MetadataEntry
	22, // 18: competitor.Competitor.created_at:type_name -> google.protobuf.Timestamp
	22, // 19: competitor.Competitor.updated_at:type_name -> google.protobuf.Timestamp
	22, // 20: competitor.CompetitorMetric.posted_at:type_name -> google.protobuf.Timestamp
	22, // 21: competitor.CompetitorMetric.created_at:type_name -> google.protobuf.Timestamp
	22, // 22: competitor.PersonalMetric.posted_at:type_name -> google.protobuf.Timestamp
	22, // 23: competitor.PersonalMetric.created_at:type_name -> google.protobuf.Timestamp
	0,  // 24: competitor.CompetitorService.AddCompetitor:input_type -> competitor.AddCompetitorRequest
	1,  // 25: competitor.CompetitorService.GetCompetitor:input_type -> competitor.GetCompetitorRequest
	2,  // 26: competitor.CompetitorService.ListCompetitors:input_type -> competitor.ListCompetitorsRequest
	4,  // 27: competitor.CompetitorService.UpdateCompetitor:input_type -> competitor.UpdateCompetitorRequest
	5,  // 28: competitor.CompetitorService.DeleteCompetitor:input_type -> competitor.DeleteCompetitorRequest
	6,  // 29: competitor.CompetitorService.GetCompetitorMetrics:input_type -> competitor.GetCompetitorMetricsRequest
	8,  // 30: competitor.CompetitorService.CompareMetrics:input_type -> competitor.CompareMetricsRequest
	15, // 31: competitor.CompetitorService.TrackCompetitorPost:input_type -> competitor.TrackCompetitorPostRequest
	16, // 32: competitor.CompetitorService.AddCompetitor:output_type -> competitor.Competitor
	16, // 33: competitor.CompetitorService.GetCompetitor:output_type -> competitor.Competitor
	3,  // 34: competitor.CompetitorService.ListCompetitors:output_type -> competitor.ListCompetitorsResponse
	16, // 35: competitor.CompetitorService.UpdateCompetitor:output_type -> competitor.Competitor
	23, // 36: competitor.CompetitorService.DeleteCompetitor:output_type -> google.protobuf.Empty
	7,  // 37: competitor.CompetitorService.GetCompetitorMetrics:output_type -> competitor.GetCompetitorMetricsResponse
	10, // 38: competitor.CompetitorService.CompareMetrics:output_type -> competitor.CompareMetricsResponse
	17, // 39: competitor.CompetitorService.TrackCompetitorPost:output_type -> competitor.CompetitorMetric
	32, // [32:40] is the sub-list for method output_type
	24, // [24:32] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_competitor_pb_competitor_proto_init() }
func file_competitor_pb_competitor_proto_init() {
	if File_competitor_pb_competitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_competitor_pb_competitor_proto_rawDesc), len(file_competitor_pb_competitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_competitor_pb_competitor_proto_goTypes,
		DependencyIndexes: file_competitor_pb_competitor_proto_depIdxs,
		MessageInfos:      file_competitor_pb_competitor_proto_msgTypes,
	}.Build()
	File_competitor_pb_competitor_proto = out.File
	file_competitor_pb_competitor_proto_goTypes = nil
	file_competitor_pb_competitor_proto_depIdxs = nil
}
