// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: scraper/pb/scraper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type ScraperJobType int32

const (
	ScraperJobType_JOB_TYPE_UNSPECIFIED ScraperJobType = 0
	ScraperJobType_JOB_TYPE_PROFILE     ScraperJobType = 1 // Scrape profile information
	ScraperJobType_JOB_TYPE_POSTS       ScraperJobType = 2 // Scrape posts
	ScraperJobType_JOB_TYPE_ENGAGEMENT  ScraperJobType = 3 // Scrape engagement metrics
	ScraperJobType_JOB_TYPE_COMMENTS    ScraperJobType = 4 // Scrape comments
	ScraperJobType_JOB_TYPE_FOLLOWERS   ScraperJobType = 5 // Scrape followers information
)

// Enum value maps for ScraperJobType.
var (
	ScraperJobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_PROFILE",
		2: "JOB_TYPE_POSTS",
		3: "JOB_TYPE_ENGAGEMENT",
		4: "JOB_TYPE_COMMENTS",
		5: "JOB_TYPE_FOLLOWERS",
	}
	ScraperJobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_PROFILE":     1,
		"JOB_TYPE_POSTS":       2,
		"JOB_TYPE_ENGAGEMENT":  3,
		"JOB_TYPE_COMMENTS":    4,
		"JOB_TYPE_FOLLOWERS":   5,
	}
)

func (x ScraperJobType) Enum() *ScraperJobType {
	p := new(ScraperJobType)
	*p = x
	return p
}

func (x ScraperJobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScraperJobType) Descriptor() protoreflect.EnumDescriptor {
	return file_scraper_pb_scraper_proto_enumTypes[0].Descriptor()
}

func (ScraperJobType) Type() protoreflect.EnumType {
	return &file_scraper_pb_scraper_proto_enumTypes[0]
}

func (x ScraperJobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScraperJobType.Descriptor instead.
func (ScraperJobType) EnumDescriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{0}
}

type ScraperJobStatus int32

const (
	ScraperJobStatus_JOB_STATUS_UNSPECIFIED ScraperJobStatus = 0
	ScraperJobStatus_JOB_STATUS_PENDING     ScraperJobStatus = 1
	ScraperJobStatus_JOB_STATUS_SCHEDULED   ScraperJobStatus = 2
	ScraperJobStatus_JOB_STATUS_RUNNING     ScraperJobStatus = 3
	ScraperJobStatus_JOB_STATUS_COMPLETED   ScraperJobStatus = 4
	ScraperJobStatus_JOB_STATUS_FAILED      ScraperJobStatus = 5
	ScraperJobStatus_JOB_STATUS_CANCELLED   ScraperJobStatus = 6
)

// Enum value maps for ScraperJobStatus.
var (
	ScraperJobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_SCHEDULED",
		3: "JOB_STATUS_RUNNING",
		4: "JOB_STATUS_COMPLETED",
		5: "JOB_STATUS_FAILED",
		6: "JOB_STATUS_CANCELLED",
	}
	ScraperJobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_SCHEDULED":   2,
		"JOB_STATUS_RUNNING":     3,
		"JOB_STATUS_COMPLETED":   4,
		"JOB_STATUS_FAILED":      5,
		"JOB_STATUS_CANCELLED":   6,
	}
)

func (x ScraperJobStatus) Enum() *ScraperJobStatus {
	p := new(ScraperJobStatus)
	*p = x
	return p
}

func (x ScraperJobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScraperJobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scraper_pb_scraper_proto_enumTypes[1].Descriptor()
}

func (ScraperJobStatus) Type() protoreflect.EnumType {
	return &file_scraper_pb_scraper_proto_enumTypes[1]
}

func (x ScraperJobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScraperJobStatus.Descriptor instead.
func (ScraperJobStatus) EnumDescriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{1}
}

type ScheduleFrequency int32

const (
	ScheduleFrequency_FREQUENCY_UNSPECIFIED ScheduleFrequency = 0
	ScheduleFrequency_FREQUENCY_ONCE        ScheduleFrequency = 1
	ScheduleFrequency_FREQUENCY_HOURLY      ScheduleFrequency = 2
	ScheduleFrequency_FREQUENCY_DAILY       ScheduleFrequency = 3
	ScheduleFrequency_FREQUENCY_WEEKLY      ScheduleFrequency = 4
)

// Enum value maps for ScheduleFrequency.
var (
	ScheduleFrequency_name = map[int32]string{
		0: "FREQUENCY_UNSPECIFIED",
		1: "FREQUENCY_ONCE",
		2: "FREQUENCY_HOURLY",
		3: "FREQUENCY_DAILY",
		4: "FREQUENCY_WEEKLY",
	}
	ScheduleFrequency_value = map[string]int32{
		"FREQUENCY_UNSPECIFIED": 0,
		"FREQUENCY_ONCE":        1,
		"FREQUENCY_HOURLY":      2,
		"FREQUENCY_DAILY":       3,
		"FREQUENCY_WEEKLY":      4,
	}
)

func (x ScheduleFrequency) Enum() *ScheduleFrequency {
	p := new(ScheduleFrequency)
	*p = x
	return p
}

func (x ScheduleFrequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleFrequency) Descriptor() protoreflect.EnumDescriptor {
	return file_scraper_pb_scraper_proto_enumTypes[2].Descriptor()
}

func (ScheduleFrequency) Type() protoreflect.EnumType {
	return &file_scraper_pb_scraper_proto_enumTypes[2]
}

func (x ScheduleFrequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleFrequency.Descriptor instead.
func (ScheduleFrequency) EnumDescriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{2}
}

type ScraperDataType int32

const (
	ScraperDataType_DATA_TYPE_UNSPECIFIED ScraperDataType = 0
	ScraperDataType_DATA_TYPE_PROFILE     ScraperDataType = 1
	ScraperDataType_DATA_TYPE_POST        ScraperDataType = 2
	ScraperDataType_DATA_TYPE_STORY       ScraperDataType = 3
	ScraperDataType_DATA_TYPE_COMMENT     ScraperDataType = 4
	ScraperDataType_DATA_TYPE_FOLLOWER    ScraperDataType = 5
)

// Enum value maps for ScraperDataType.
var (
	ScraperDataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_PROFILE",
		2: "DATA_TYPE_POST",
		3: "DATA_TYPE_STORY",
		4: "DATA_TYPE_COMMENT",
		5: "DATA_TYPE_FOLLOWER",
	}
	ScraperDataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_PROFILE":     1,
		"DATA_TYPE_POST":        2,
		"DATA_TYPE_STORY":       3,
		"DATA_TYPE_COMMENT":     4,
		"DATA_TYPE_FOLLOWER":    5,
	}
)

func (x ScraperDataType) Enum() *ScraperDataType {
	p := new(ScraperDataType)
	*p = x
	return p
}

func (x ScraperDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScraperDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_scraper_pb_scraper_proto_enumTypes[3].Descriptor()
}

func (ScraperDataType) Type() protoreflect.EnumType {
	return &file_scraper_pb_scraper_proto_enumTypes[3]
}

func (x ScraperDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScraperDataType.Descriptor instead.
func (ScraperDataType) EnumDescriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{3}
}

// Scraper management
type CreateScraperJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // Platform-specific ID (e.g., username, profile ID)
	JobType       ScraperJobType         `protobuf:"varint,4,opt,name=job_type,json=jobType,proto3,enum=scraper.ScraperJobType" json:"job_type,omitempty"`
	Schedule      *ScraperSchedule       `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScraperJobRequest) Reset() {
	*x = CreateScraperJobRequest{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScraperJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScraperJobRequest) ProtoMessage() {}

func (x *CreateScraperJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScraperJobRequest.ProtoReflect.Descriptor instead.
func (*CreateScraperJobRequest) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScraperJobRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateScraperJobRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateScraperJobRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CreateScraperJobRequest) GetJobType() ScraperJobType {
	if x != nil {
		return x.JobType
	}
	return ScraperJobType_JOB_TYPE_UNSPECIFIED
}

func (x *CreateScraperJobRequest) GetSchedule() *ScraperSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *CreateScraperJobRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetScraperJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScraperJobRequest) Reset() {
	*x = GetScraperJobRequest{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScraperJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScraperJobRequest) ProtoMessage() {}

func (x *GetScraperJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScraperJobRequest.ProtoReflect.Descriptor instead.
func (*GetScraperJobRequest) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *GetScraperJobRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetScraperJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ListScraperJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`                                           // Optional, filter by platform
	JobType       ScraperJobType         `protobuf:"varint,3,opt,name=job_type,json=jobType,proto3,enum=scraper.ScraperJobType" json:"job_type,omitempty"` // Optional, filter by job type
	Status        ScraperJobStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=scraper.ScraperJobStatus" json:"status,omitempty"`                // Optional, filter by status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScraperJobsRequest) Reset() {
	*x = ListScraperJobsRequest{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScraperJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScraperJobsRequest) ProtoMessage() {}

func (x *ListScraperJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScraperJobsRequest.ProtoReflect.Descriptor instead.
func (*ListScraperJobsRequest) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *ListScraperJobsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListScraperJobsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListScraperJobsRequest) GetJobType() ScraperJobType {
	if x != nil {
		return x.JobType
	}
	return ScraperJobType_JOB_TYPE_UNSPECIFIED
}

func (x *ListScraperJobsRequest) GetStatus() ScraperJobStatus {
	if x != nil {
		return x.Status
	}
	return ScraperJobStatus_JOB_STATUS_UNSPECIFIED
}

type ListScraperJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*ScraperJob          `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScraperJobsResponse) Reset() {
	*x = ListScraperJobsResponse{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScraperJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScraperJobsResponse) ProtoMessage() {}

func (x *ListScraperJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScraperJobsResponse.ProtoReflect.Descriptor instead.
func (*ListScraperJobsResponse) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *ListScraperJobsResponse) GetJobs() []*ScraperJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type CancelScraperJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScraperJobRequest) Reset() {
	*x = CancelScraperJobRequest{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScraperJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScraperJobRequest) ProtoMessage() {}

func (x *CancelScraperJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScraperJobRequest.ProtoReflect.Descriptor instead.
func (*CancelScraperJobRequest) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *CancelScraperJobRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CancelScraperJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type DeleteScraperJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScraperJobRequest) Reset() {
	*x = DeleteScraperJobRequest{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScraperJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScraperJobRequest) ProtoMessage() {}

func (x *DeleteScraperJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScraperJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteScraperJobRequest) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteScraperJobRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteScraperJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Platform operations
type ListSupportedPlatformsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedPlatformsRequest) Reset() {
	*x = ListSupportedPlatformsRequest{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedPlatformsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedPlatformsRequest) ProtoMessage() {}

func (x *ListSupportedPlatformsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedPlatformsRequest.ProtoReflect.Descriptor instead.
func (*ListSupportedPlatformsRequest) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{6}
}

func (x *ListSupportedPlatformsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListSupportedPlatformsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platforms     []*PlatformInfo        `protobuf:"bytes,1,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedPlatformsResponse) Reset() {
	*x = ListSupportedPlatformsResponse{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedPlatformsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedPlatformsResponse) ProtoMessage() {}

func (x *ListSupportedPlatformsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedPlatformsResponse.ProtoReflect.Descriptor instead.
func (*ListSupportedPlatformsResponse) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{7}
}

func (x *ListSupportedPlatformsResponse) GetPlatforms() []*PlatformInfo {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type GetPlatformStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformStatusRequest) Reset() {
	*x = GetPlatformStatusRequest{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformStatusRequest) ProtoMessage() {}

func (x *GetPlatformStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformStatusRequest) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlatformStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetPlatformStatusRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// Scraper results
type GetScrapedDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScrapedDataRequest) Reset() {
	*x = GetScrapedDataRequest{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScrapedDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScrapedDataRequest) ProtoMessage() {}

func (x *GetScrapedDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScrapedDataRequest.ProtoReflect.Descriptor instead.
func (*GetScrapedDataRequest) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{9}
}

func (x *GetScrapedDataRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetScrapedDataRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetScrapedDataRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetScrapedDataRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetScrapedDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ScrapedDataItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScrapedDataResponse) Reset() {
	*x = GetScrapedDataResponse{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScrapedDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScrapedDataResponse) ProtoMessage() {}

func (x *GetScrapedDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScrapedDataResponse.ProtoReflect.Descriptor instead.
func (*GetScrapedDataResponse) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{10}
}

func (x *GetScrapedDataResponse) GetItems() []*ScrapedDataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Models
type ScraperJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	JobType       ScraperJobType         `protobuf:"varint,5,opt,name=job_type,json=jobType,proto3,enum=scraper.ScraperJobType" json:"job_type,omitempty"`
	Status        ScraperJobStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=scraper.ScraperJobStatus" json:"status,omitempty"`
	Schedule      *ScraperSchedule       `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	LastError     string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	RunCount      int32                  `protobuf:"varint,9,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	LastRunAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	NextRunAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScraperJob) Reset() {
	*x = ScraperJob{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScraperJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScraperJob) ProtoMessage() {}

func (x *ScraperJob) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScraperJob.ProtoReflect.Descriptor instead.
func (*ScraperJob) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{11}
}

func (x *ScraperJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScraperJob) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScraperJob) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ScraperJob) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ScraperJob) GetJobType() ScraperJobType {
	if x != nil {
		return x.JobType
	}
	return ScraperJobType_JOB_TYPE_UNSPECIFIED
}

func (x *ScraperJob) GetStatus() ScraperJobStatus {
	if x != nil {
		return x.Status
	}
	return ScraperJobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ScraperJob) GetSchedule() *ScraperSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *ScraperJob) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ScraperJob) GetRunCount() int32 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *ScraperJob) GetLastRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunAt
	}
	return nil
}

func (x *ScraperJob) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *ScraperJob) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ScraperJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScraperJob) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ScraperSchedule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CronExpression string                 `protobuf:"bytes,1,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"` // Cron expression for scheduled jobs
	Frequency      ScheduleFrequency      `protobuf:"varint,2,opt,name=frequency,proto3,enum=scraper.ScheduleFrequency" json:"frequency,omitempty"` // Predefined frequency
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`                // Optional start date for scheduled jobs
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                      // Optional end date for scheduled jobs
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScraperSchedule) Reset() {
	*x = ScraperSchedule{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScraperSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScraperSchedule) ProtoMessage() {}

func (x *ScraperSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScraperSchedule.ProtoReflect.Descriptor instead.
func (*ScraperSchedule) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{12}
}

func (x *ScraperSchedule) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *ScraperSchedule) GetFrequency() ScheduleFrequency {
	if x != nil {
		return x.Frequency
	}
	return ScheduleFrequency_FREQUENCY_UNSPECIFIED
}

func (x *ScraperSchedule) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ScraperSchedule) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type PlatformInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                          // Platform name (e.g., "instagram", "twitter")
	DisplayName       string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`                                                         // Display name (e.g., "Instagram", "Twitter")
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                                                            // Platform description
	SupportedJobTypes []ScraperJobType       `protobuf:"varint,4,rep,packed,name=supported_job_types,json=supportedJobTypes,proto3,enum=scraper.ScraperJobType" json:"supported_job_types,omitempty"` // Supported job types
	RateLimits        *PlatformRateLimits    `protobuf:"bytes,5,opt,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"`                                                            // Rate limits
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlatformInfo) Reset() {
	*x = PlatformInfo{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformInfo) ProtoMessage() {}

func (x *PlatformInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformInfo.ProtoReflect.Descriptor instead.
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{13}
}

func (x *PlatformInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlatformInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PlatformInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlatformInfo) GetSupportedJobTypes() []ScraperJobType {
	if x != nil {
		return x.SupportedJobTypes
	}
	return nil
}

func (x *PlatformInfo) GetRateLimits() *PlatformRateLimits {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

type PlatformStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	StatusMessage string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	RateLimits    *PlatformRateLimits    `protobuf:"bytes,4,opt,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"`
	LastChecked   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformStatus) Reset() {
	*x = PlatformStatus{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformStatus) ProtoMessage() {}

func (x *PlatformStatus) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformStatus.ProtoReflect.Descriptor instead.
func (*PlatformStatus) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{14}
}

func (x *PlatformStatus) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *PlatformStatus) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *PlatformStatus) GetRateLimits() *PlatformRateLimits {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

func (x *PlatformStatus) GetLastChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChecked
	}
	return nil
}

type PlatformRateLimits struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerMinute int32                  `protobuf:"varint,1,opt,name=requests_per_minute,json=requestsPerMinute,proto3" json:"requests_per_minute,omitempty"`
	RequestsPerHour   int32                  `protobuf:"varint,2,opt,name=requests_per_hour,json=requestsPerHour,proto3" json:"requests_per_hour,omitempty"`
	RequestsPerDay    int32                  `protobuf:"varint,3,opt,name=requests_per_day,json=requestsPerDay,proto3" json:"requests_per_day,omitempty"`
	AvailableRequests int32                  `protobuf:"varint,4,opt,name=available_requests,json=availableRequests,proto3" json:"available_requests,omitempty"`
	ResetAt           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlatformRateLimits) Reset() {
	*x = PlatformRateLimits{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformRateLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformRateLimits) ProtoMessage() {}

func (x *PlatformRateLimits) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformRateLimits.ProtoReflect.Descriptor instead.
func (*PlatformRateLimits) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{15}
}

func (x *PlatformRateLimits) GetRequestsPerMinute() int32 {
	if x != nil {
		return x.RequestsPerMinute
	}
	return 0
}

func (x *PlatformRateLimits) GetRequestsPerHour() int32 {
	if x != nil {
		return x.RequestsPerHour
	}
	return 0
}

func (x *PlatformRateLimits) GetRequestsPerDay() int32 {
	if x != nil {
		return x.RequestsPerDay
	}
	return 0
}

func (x *PlatformRateLimits) GetAvailableRequests() int32 {
	if x != nil {
		return x.AvailableRequests
	}
	return 0
}

func (x *PlatformRateLimits) GetResetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetAt
	}
	return nil
}

type ScrapedDataItem struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId    string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TenantId string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Platform string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	TargetId string                 `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	PostId   string                 `protobuf:"bytes,6,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	DataType ScraperDataType        `protobuf:"varint,7,opt,name=data_type,json=dataType,proto3,enum=scraper.ScraperDataType" json:"data_type,omitempty"`
	PostedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	// Engagement metrics
	Likes            int32   `protobuf:"varint,9,opt,name=likes,proto3" json:"likes,omitempty"`
	Shares           int32   `protobuf:"varint,10,opt,name=shares,proto3" json:"shares,omitempty"`
	Comments         int32   `protobuf:"varint,11,opt,name=comments,proto3" json:"comments,omitempty"`
	ClickThroughRate float64 `protobuf:"fixed64,12,opt,name=click_through_rate,json=clickThroughRate,proto3" json:"click_through_rate,omitempty"`
	AvgWatchTime     float64 `protobuf:"fixed64,13,opt,name=avg_watch_time,json=avgWatchTime,proto3" json:"avg_watch_time,omitempty"`
	EngagementRate   float64 `protobuf:"fixed64,14,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"`
	// Content information
	ContentType       string                 `protobuf:"bytes,15,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentUrl        string                 `protobuf:"bytes,16,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	ContentAttributes map[string]string      `protobuf:"bytes,17,rep,name=content_attributes,json=contentAttributes,proto3" json:"content_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ScrapedAt         *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=scraped_at,json=scrapedAt,proto3" json:"scraped_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScrapedDataItem) Reset() {
	*x = ScrapedDataItem{}
	mi := &file_scraper_pb_scraper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapedDataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapedDataItem) ProtoMessage() {}

func (x *ScrapedDataItem) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_pb_scraper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapedDataItem.ProtoReflect.Descriptor instead.
func (*ScrapedDataItem) Descriptor() ([]byte, []int) {
	return file_scraper_pb_scraper_proto_rawDescGZIP(), []int{16}
}

func (x *ScrapedDataItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScrapedDataItem) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScrapedDataItem) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScrapedDataItem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ScrapedDataItem) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ScrapedDataItem) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ScrapedDataItem) GetDataType() ScraperDataType {
	if x != nil {
		return x.DataType
	}
	return ScraperDataType_DATA_TYPE_UNSPECIFIED
}

func (x *ScrapedDataItem) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *ScrapedDataItem) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *ScrapedDataItem) GetShares() int32 {
	if x != nil {
		return x.Shares
	}
	return 0
}

func (x *ScrapedDataItem) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *ScrapedDataItem) GetClickThroughRate() float64 {
	if x != nil {
		return x.ClickThroughRate
	}
	return 0
}

func (x *ScrapedDataItem) GetAvgWatchTime() float64 {
	if x != nil {
		return x.AvgWatchTime
	}
	return 0
}

func (x *ScrapedDataItem) GetEngagementRate() float64 {
	if x != nil {
		return x.EngagementRate
	}
	return 0
}

func (x *ScrapedDataItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ScrapedDataItem) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *ScrapedDataItem) GetContentAttributes() map[string]string {
	if x != nil {
		return x.ContentAttributes
	}
	return nil
}

func (x *ScrapedDataItem) GetScrapedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScrapedAt
	}
	return nil
}

func (x *ScrapedDataItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_scraper_pb_scraper_proto protoreflect.FileDescriptor

const file_scraper_pb_scraper_proto_rawDesc = "" +
	"\n" +
	"\x18scraper/pb/scraper.proto\x12\ascraper\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe2\x02\n" +
	"\x17CreateScraperJobRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x122\n" +
	"\bjob_type\x18\x04 \x01(\x0e2\x17.scraper.ScraperJobTypeR\ajobType\x124\n" +
	"\bschedule\x18\x05 \x01(\v2\x18.scraper.ScraperScheduleR\bschedule\x12J\n" +
	"\bmetadata\x18\x06 \x03(\v2..scraper.CreateScraperJobRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x14GetScraperJobRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"\xb8\x01\n" +
	"\x16ListScraperJobsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x122\n" +
	"\bjob_type\x18\x03 \x01(\x0e2\x17.scraper.ScraperJobTypeR\ajobType\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.scraper.ScraperJobStatusR\x06status\"B\n" +
	"\x17ListScraperJobsResponse\x12'\n" +
	"\x04jobs\x18\x01 \x03(\v2\x13.scraper.ScraperJobR\x04jobs\"M\n" +
	"\x17CancelScraperJobRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"M\n" +
	"\x17DeleteScraperJobRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"<\n" +
	"\x1dListSupportedPlatformsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"U\n" +
	"\x1eListSupportedPlatformsResponse\x123\n" +
	"\tplatforms\x18\x01 \x03(\v2\x15.scraper.PlatformInfoR\tplatforms\"S\n" +
	"\x18GetPlatformStatusRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"\xbd\x01\n" +
	"\x15GetScrapedDataRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"H\n" +
	"\x16GetScrapedDataResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.scraper.ScrapedDataItemR\x05items\"\xb5\x05\n" +
	"\n" +
	"ScraperJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x122\n" +
	"\bjob_type\x18\x05 \x01(\x0e2\x17.scraper.ScraperJobTypeR\ajobType\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.scraper.ScraperJobStatusR\x06status\x124\n" +
	"\bschedule\x18\a \x01(\v2\x18.scraper.ScraperScheduleR\bschedule\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\x12\x1b\n" +
	"\trun_count\x18\t \x01(\x05R\brunCount\x12:\n" +
	"\vlast_run_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tlastRunAt\x12:\n" +
	"\vnext_run_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x12=\n" +
	"\bmetadata\x18\f \x03(\v2!.scraper.ScraperJob.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x0fScraperSchedule\x12'\n" +
	"\x0fcron_expression\x18\x01 \x01(\tR\x0ecronExpression\x128\n" +
	"\tfrequency\x18\x02 \x01(\x0e2\x1a.scraper.ScheduleFrequencyR\tfrequency\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xee\x01\n" +
	"\fPlatformInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12G\n" +
	"\x13supported_job_types\x18\x04 \x03(\x0e2\x17.scraper.ScraperJobTypeR\x11supportedJobTypes\x12<\n" +
	"\vrate_limits\x18\x05 \x01(\v2\x1b.scraper.PlatformRateLimitsR\n" +
	"rateLimits\"\xee\x01\n" +
	"\x0ePlatformStatus\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\x12<\n" +
	"\vrate_limits\x18\x04 \x01(\v2\x1b.scraper.PlatformRateLimitsR\n" +
	"rateLimits\x12=\n" +
	"\flast_checked\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastChecked\"\x80\x02\n" +
	"\x12PlatformRateLimits\x12.\n" +
	"\x13requests_per_minute\x18\x01 \x01(\x05R\x11requestsPerMinute\x12*\n" +
	"\x11requests_per_hour\x18\x02 \x01(\x05R\x0frequestsPerHour\x12(\n" +
	"\x10requests_per_day\x18\x03 \x01(\x05R\x0erequestsPerDay\x12-\n" +
	"\x12available_requests\x18\x04 \x01(\x05R\x11availableRequests\x125\n" +
	"\breset_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aresetAt\"\xbe\x06\n" +
	"\x0fScrapedDataItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x12\x17\n" +
	"\apost_id\x18\x06 \x01(\tR\x06postId\x125\n" +
	"\tdata_type\x18\a \x01(\x0e2\x18.scraper.ScraperDataTypeR\bdataType\x127\n" +
	"\tposted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x12\x14\n" +
	"\x05likes\x18\t \x01(\x05R\x05likes\x12\x16\n" +
	"\x06shares\x18\n" +
	" \x01(\x05R\x06shares\x12\x1a\n" +
	"\bcomments\x18\v \x01(\x05R\bcomments\x12,\n" +
	"\x12click_through_rate\x18\f \x01(\x01R\x10clickThroughRate\x12$\n" +
	"\x0eavg_watch_time\x18\r \x01(\x01R\favgWatchTime\x12'\n" +
	"\x0fengagement_rate\x18\x0e \x01(\x01R\x0eengagementRate\x12!\n" +
	"\fcontent_type\x18\x0f \x01(\tR\vcontentType\x12\x1f\n" +
	"\vcontent_url\x18\x10 \x01(\tR\n" +
	"contentUrl\x12^\n" +
	"\x12content_attributes\x18\x11 \x03(\v2/.scraper.ScrapedDataItem.ContentAttributesEntryR\x11contentAttributes\x129\n" +
	"\n" +
	"scraped_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tscrapedAt\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1aD\n" +
	"\x16ContentAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x9c\x01\n" +
	"\x0eScraperJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10JOB_TYPE_PROFILE\x10\x01\x12\x12\n" +
	"\x0eJOB_TYPE_POSTS\x10\x02\x12\x17\n" +
	"\x13JOB_TYPE_ENGAGEMENT\x10\x03\x12\x15\n" +
	"\x11JOB_TYPE_COMMENTS\x10\x04\x12\x16\n" +
	"\x12JOB_TYPE_FOLLOWERS\x10\x05*\xc3\x01\n" +
	"\x10ScraperJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14JOB_STATUS_SCHEDULED\x10\x02\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x03\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x04\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x05\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x06*\x83\x01\n" +
	"\x11ScheduleFrequency\x12\x19\n" +
	"\x15FREQUENCY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eFREQUENCY_ONCE\x10\x01\x12\x14\n" +
	"\x10FREQUENCY_HOURLY\x10\x02\x12\x13\n" +
	"\x0fFREQUENCY_DAILY\x10\x03\x12\x14\n" +
	"\x10FREQUENCY_WEEKLY\x10\x04*\x9b\x01\n" +
	"\x0fScraperDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DATA_TYPE_PROFILE\x10\x01\x12\x12\n" +
	"\x0eDATA_TYPE_POST\x10\x02\x12\x13\n" +
	"\x0fDATA_TYPE_STORY\x10\x03\x12\x15\n" +
	"\x11DATA_TYPE_COMMENT\x10\x04\x12\x16\n" +
	"\x12DATA_TYPE_FOLLOWER\x10\x052\xae\x05\n" +
	"\x0eScraperService\x12K\n" +
	"\x10CreateScraperJob\x12 .scraper.CreateScraperJobRequest\x1a\x13.scraper.ScraperJob\"\x00\x12E\n" +
	"\rGetScraperJob\x12\x1d.scraper.GetScraperJobRequest\x1a\x13.scraper.ScraperJob\"\x00\x12V\n" +
	"\x0fListScraperJobs\x12\x1f.scraper.ListScraperJobsRequest\x1a .scraper.ListScraperJobsResponse\"\x00\x12K\n" +
	"\x10CancelScraperJob\x12 .scraper.CancelScraperJobRequest\x1a\x13.scraper.ScraperJob\"\x00\x12N\n" +
	"\x10DeleteScraperJob\x12 .scraper.DeleteScraperJobRequest\x1a\x16.google.protobuf.Empty\"\x00\x12k\n" +
	"\x16ListSupportedPlatforms\x12&.scraper.ListSupportedPlatformsRequest\x1a'.scraper.ListSupportedPlatformsResponse\"\x00\x12Q\n" +
	"\x11GetPlatformStatus\x12!.scraper.GetPlatformStatusRequest\x1a\x17.scraper.PlatformStatus\"\x00\x12S\n" +
	"\x0eGetScrapedData\x12\x1e.scraper.GetScrapedDataRequest\x1a\x1f.scraper.GetScrapedDataResponse\"\x00B0Z.github.com/donaldnash/go-competitor/scraper/pbb\x06proto3"

var (
	file_scraper_pb_scraper_proto_rawDescOnce sync.Once
	file_scraper_pb_scraper_proto_rawDescData []byte
)

func file_scraper_pb_scraper_proto_rawDescGZIP() []byte {
	file_scraper_pb_scraper_proto_rawDescOnce.Do(func() {
		file_scraper_pb_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scraper_pb_scraper_proto_rawDesc), len(file_scraper_pb_scraper_proto_rawDesc)))
	})
	return file_scraper_pb_scraper_proto_rawDescData
}

var file_scraper_pb_scraper_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_scraper_pb_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_scraper_pb_scraper_proto_goTypes = []any{
	(ScraperJobType)(0),                    // 0: scraper.ScraperJobType
	(ScraperJobStatus)(0),                  // 1: scraper.ScraperJobStatus
	(ScheduleFrequency)(0),                 // 2: scraper.ScheduleFrequency
	(ScraperDataType)(0),                   // 3: scraper.ScraperDataType
	(*CreateScraperJobRequest)(nil),        // 4: scraper.CreateScraperJobRequest
	(*GetScraperJobRequest)(nil),           // 5: scraper.GetScraperJobRequest
	(*ListScraperJobsRequest)(nil),         // 6: scraper.ListScraperJobsRequest
	(*ListScraperJobsResponse)(nil),        // 7: scraper.ListScraperJobsResponse
	(*CancelScraperJobRequest)(nil),        // 8: scraper.CancelScraperJobRequest
	(*DeleteScraperJobRequest)(nil),        // 9: scraper.DeleteScraperJobRequest
	(*ListSupportedPlatformsRequest)(nil),  // 10: scraper.ListSupportedPlatformsRequest
	(*ListSupportedPlatformsResponse)(nil), // 11: scraper.ListSupportedPlatformsResponse
	(*GetPlatformStatusRequest)(nil),       // 12: scraper.GetPlatformStatusRequest
	(*GetScrapedDataRequest)(nil),          // 13: scraper.GetScrapedDataRequest
	(*GetScrapedDataResponse)(nil),         // 14: scraper.GetScrapedDataResponse
	(*ScraperJob)(nil),                     // 15: scraper.ScraperJob
	(*ScraperSchedule)(nil),                // 16: scraper.ScraperSchedule
	(*PlatformInfo)(nil),                   // 17: scraper.PlatformInfo
	(*PlatformStatus)(nil),                 // 18: scraper.PlatformStatus
	(*PlatformRateLimits)(nil),             // 19: scraper.PlatformRateLimits
	(*ScrapedDataItem)(nil),                // 20: scraper.ScrapedDataItem
	nil,                                    // 21: scraper.CreateScraperJobRequest.MetadataEntry
	nil,                                    // 22: scraper.ScraperJob.MetadataEntry
	nil,                                    // 23: scraper.ScrapedDataItem.ContentAttributesEntry
	(*timestamppb.Timestamp)(nil),          // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 25: google.protobuf.Empty
}
var file_scraper_pb_scraper_proto_depIdxs = []int32{
	0,  // 0: scraper.CreateScraperJobRequest.job_type:type_name -> scraper.ScraperJobType
	16, // 1: scraper.CreateScraperJobRequest.schedule:type_name -> scraper.ScraperSchedule
	21, // 2: scraper.CreateScraperJobRequest.metadata:type_name -> scraper.CreateScraperJobRequest.MetadataEntry
	0,  // 3: scraper.ListScraperJobsRequest.job_type:type_name -> scraper.ScraperJobType
	1,  // 4: scraper.ListScraperJobsRequest.status:type_name -> scraper.ScraperJobStatus
	15, // 5: scraper.ListScraperJobsResponse.jobs:type_name -> scraper.ScraperJob
	17, // 6: scraper.ListSupportedPlatformsResponse.platforms:type_name -> scraper.PlatformInfo
	24, // 7: scraper.GetScrapedDataRequest.start_date:type_name -> google.protobuf.Timestamp
	24, // 8: scraper.GetScrapedDataRequest.end_date:type_name -> google.protobuf.Timestamp
	20, // 9: scraper.GetScrapedDataResponse.items:type_name -> scraper.ScrapedDataItem
	0,  // 10: scraper.ScraperJob.job_type:type_name -> scraper.ScraperJobType
	1,  // 11: scraper.ScraperJob.status:type_name -> scraper.ScraperJobStatus
	16, // 12: scraper.ScraperJob.schedule:type_name -> scraper.ScraperSchedule
	24, // 13: scraper.ScraperJob.last_run_at:type_name -> google.protobuf.Timestamp
	24, // 14: scraper.ScraperJob.next_run_at:type_name -> google.protobuf.Timestamp
	22, // 15: scraper.ScraperJob.metadata:type_name -> scraper.ScraperJob.MetadataEntry
	24, // 16: scraper.ScraperJob.created_at:type_name -> google.protobuf.Timestamp
	24, // 17: scraper.ScraperJob.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 18: scraper.ScraperSchedule.frequency:type_name -> scraper.ScheduleFrequency
	24, // 19: scraper.ScraperSchedule.start_date:type_name -> google.protobuf.Timestamp
	24, // 20: scraper.ScraperSchedule.end_date:type_name -> google.protobuf.Timestamp
	0,  // 21: scraper.PlatformInfo.supported_job_types:type_name -> scraper.ScraperJobType
	19, // 22: scraper.PlatformInfo.rate_limits:type_name -> scraper.PlatformRateLimits
	19, // 23: scraper.PlatformStatus.rate_limits:type_name -> scraper.PlatformRateLimits
	24, // 24: scraper.PlatformStatus.last_checked:type_name -> google.protobuf.Timestamp
	24, // 25: scraper.PlatformRateLimits.reset_at:type_name -> google.protobuf.Timestamp
	3,  // 26: scraper.ScrapedDataItem.data_type:type_name -> scraper.ScraperDataType
	24, // 27: scraper.ScrapedDataItem.posted_at:type_name -> google.protobuf.Timestamp
	23, // 28: scraper.ScrapedDataItem.content_attributes:type_name -> scraper.ScrapedDataItem.ContentAttributesEntry
	24, // 29: scraper.ScrapedDataItem.scraped_at:type_name -> google.protobuf.Timestamp
	24, // 30: scraper.ScrapedDataItem.created_at:type_name -> google.protobuf.Timestamp
	4,  // 31: scraper.ScraperService.CreateScraperJob:input_type -> scraper.CreateScraperJobRequest
	5,  // 32: scraper.ScraperService.GetScraperJob:input_type -> scraper.GetScraperJobRequest
	6,  // 33: scraper.ScraperService.ListScraperJobs:input_type -> scraper.ListScraperJobsRequest
	8,  // 34: scraper.ScraperService.CancelScraperJob:input_type -> scraper.CancelScraperJobRequest
	9,  // 35: scraper.ScraperService.DeleteScraperJob:input_type -> scraper.DeleteScraperJobRequest
	10, // 36: scraper.ScraperService.ListSupportedPlatforms:input_type -> scraper.ListSupportedPlatformsRequest
	12, // 37: scraper.ScraperService.GetPlatformStatus:input_type -> scraper.GetPlatformStatusRequest
	13, // 38: scraper.ScraperService.GetScrapedData:input_type -> scraper.GetScrapedDataRequest
	15, // 39: scraper.ScraperService.CreateScraperJob:output_type -> scraper.ScraperJob
	15, // 40: scraper.ScraperService.GetScraperJob:output_type -> scraper.ScraperJob
	7,  // 41: scraper.ScraperService.ListScraperJobs:output_type -> scraper.ListScraperJobsResponse
	15, // 42: scraper.ScraperService.CancelScraperJob:output_type -> scraper.ScraperJob
	25, // 43: scraper.ScraperService.DeleteScraperJob:output_type -> google.protobuf.Empty
	11, // 44: scraper.ScraperService.ListSupportedPlatforms:output_type -> scraper.ListSupportedPlatformsResponse
	18, // 45: scraper.ScraperService.GetPlatformStatus:output_type -> scraper.PlatformStatus
	14, // 46: scraper.ScraperService.GetScrapedData:output_type -> scraper.GetScrapedDataResponse
	39, // [39:47] is the sub-list for method output_type
	31, // [31:39] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_scraper_pb_scraper_proto_init() }
func file_scraper_pb_scraper_proto_init() {
	if File_scraper_pb_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scraper_pb_scraper_proto_rawDesc), len(file_scraper_pb_scraper_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scraper_pb_scraper_proto_goTypes,
		DependencyIndexes: file_scraper_pb_scraper_proto_depIdxs,
		EnumInfos:         file_scraper_pb_scraper_proto_enumTypes,
		MessageInfos:      file_scraper_pb_scraper_proto_msgTypes,
	}.Build()
	File_scraper_pb_scraper_proto = out.File
	file_scraper_pb_scraper_proto_goTypes = nil
	file_scraper_pb_scraper_proto_depIdxs = nil
}
