// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: content/pb/content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for getting all content formats
type GetContentFormatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentFormatsRequest) Reset() {
	*x = GetContentFormatsRequest{}
	mi := &file_content_pb_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentFormatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentFormatsRequest) ProtoMessage() {}

func (x *GetContentFormatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentFormatsRequest.ProtoReflect.Descriptor instead.
func (*GetContentFormatsRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{0}
}

func (x *GetContentFormatsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// Response for getting all content formats
type GetContentFormatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formats       []*ContentFormat       `protobuf:"bytes,1,rep,name=formats,proto3" json:"formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentFormatsResponse) Reset() {
	*x = GetContentFormatsResponse{}
	mi := &file_content_pb_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentFormatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentFormatsResponse) ProtoMessage() {}

func (x *GetContentFormatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentFormatsResponse.ProtoReflect.Descriptor instead.
func (*GetContentFormatsResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{1}
}

func (x *GetContentFormatsResponse) GetFormats() []*ContentFormat {
	if x != nil {
		return x.Formats
	}
	return nil
}

// Request for getting a specific content format
type GetContentFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FormatId      string                 `protobuf:"bytes,2,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentFormatRequest) Reset() {
	*x = GetContentFormatRequest{}
	mi := &file_content_pb_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentFormatRequest) ProtoMessage() {}

func (x *GetContentFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentFormatRequest.ProtoReflect.Descriptor instead.
func (*GetContentFormatRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{2}
}

func (x *GetContentFormatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetContentFormatRequest) GetFormatId() string {
	if x != nil {
		return x.FormatId
	}
	return ""
}

// Response for getting a specific content format
type GetContentFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *ContentFormat         `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentFormatResponse) Reset() {
	*x = GetContentFormatResponse{}
	mi := &file_content_pb_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentFormatResponse) ProtoMessage() {}

func (x *GetContentFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentFormatResponse.ProtoReflect.Descriptor instead.
func (*GetContentFormatResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentFormatResponse) GetFormat() *ContentFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

// Request for creating a new content format
type CreateContentFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentFormatRequest) Reset() {
	*x = CreateContentFormatRequest{}
	mi := &file_content_pb_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentFormatRequest) ProtoMessage() {}

func (x *CreateContentFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentFormatRequest.ProtoReflect.Descriptor instead.
func (*CreateContentFormatRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{4}
}

func (x *CreateContentFormatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateContentFormatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContentFormatRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Response for creating a new content format
type CreateContentFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *ContentFormat         `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentFormatResponse) Reset() {
	*x = CreateContentFormatResponse{}
	mi := &file_content_pb_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentFormatResponse) ProtoMessage() {}

func (x *CreateContentFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentFormatResponse.ProtoReflect.Descriptor instead.
func (*CreateContentFormatResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{5}
}

func (x *CreateContentFormatResponse) GetFormat() *ContentFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

// Request for updating an existing content format
type UpdateContentFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FormatId      string                 `protobuf:"bytes,2,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentFormatRequest) Reset() {
	*x = UpdateContentFormatRequest{}
	mi := &file_content_pb_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentFormatRequest) ProtoMessage() {}

func (x *UpdateContentFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentFormatRequest.ProtoReflect.Descriptor instead.
func (*UpdateContentFormatRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateContentFormatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateContentFormatRequest) GetFormatId() string {
	if x != nil {
		return x.FormatId
	}
	return ""
}

func (x *UpdateContentFormatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateContentFormatRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Response for updating an existing content format
type UpdateContentFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *ContentFormat         `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentFormatResponse) Reset() {
	*x = UpdateContentFormatResponse{}
	mi := &file_content_pb_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentFormatResponse) ProtoMessage() {}

func (x *UpdateContentFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentFormatResponse.ProtoReflect.Descriptor instead.
func (*UpdateContentFormatResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateContentFormatResponse) GetFormat() *ContentFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

// Request for deleting a content format
type DeleteContentFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FormatId      string                 `protobuf:"bytes,2,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentFormatRequest) Reset() {
	*x = DeleteContentFormatRequest{}
	mi := &file_content_pb_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentFormatRequest) ProtoMessage() {}

func (x *DeleteContentFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentFormatRequest.ProtoReflect.Descriptor instead.
func (*DeleteContentFormatRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteContentFormatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteContentFormatRequest) GetFormatId() string {
	if x != nil {
		return x.FormatId
	}
	return ""
}

// Response for deleting a content format
type DeleteContentFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentFormatResponse) Reset() {
	*x = DeleteContentFormatResponse{}
	mi := &file_content_pb_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentFormatResponse) ProtoMessage() {}

func (x *DeleteContentFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentFormatResponse.ProtoReflect.Descriptor instead.
func (*DeleteContentFormatResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteContentFormatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request for getting performance metrics for a specific content format
type GetFormatPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FormatId      string                 `protobuf:"bytes,2,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // RFC3339 format
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormatPerformanceRequest) Reset() {
	*x = GetFormatPerformanceRequest{}
	mi := &file_content_pb_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormatPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormatPerformanceRequest) ProtoMessage() {}

func (x *GetFormatPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormatPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetFormatPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{10}
}

func (x *GetFormatPerformanceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetFormatPerformanceRequest) GetFormatId() string {
	if x != nil {
		return x.FormatId
	}
	return ""
}

func (x *GetFormatPerformanceRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetFormatPerformanceRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Response for getting performance metrics for a specific content format
type GetFormatPerformanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Performance   []*FormatPerformance   `protobuf:"bytes,1,rep,name=performance,proto3" json:"performance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormatPerformanceResponse) Reset() {
	*x = GetFormatPerformanceResponse{}
	mi := &file_content_pb_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormatPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormatPerformanceResponse) ProtoMessage() {}

func (x *GetFormatPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormatPerformanceResponse.ProtoReflect.Descriptor instead.
func (*GetFormatPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{11}
}

func (x *GetFormatPerformanceResponse) GetPerformance() []*FormatPerformance {
	if x != nil {
		return x.Performance
	}
	return nil
}

// Request for updating performance metrics for a specific content format
type UpdateFormatPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FormatId      string                 `protobuf:"bytes,2,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	Performance   []*FormatPerformance   `protobuf:"bytes,3,rep,name=performance,proto3" json:"performance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFormatPerformanceRequest) Reset() {
	*x = UpdateFormatPerformanceRequest{}
	mi := &file_content_pb_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormatPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormatPerformanceRequest) ProtoMessage() {}

func (x *UpdateFormatPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormatPerformanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateFormatPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateFormatPerformanceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateFormatPerformanceRequest) GetFormatId() string {
	if x != nil {
		return x.FormatId
	}
	return ""
}

func (x *UpdateFormatPerformanceRequest) GetPerformance() []*FormatPerformance {
	if x != nil {
		return x.Performance
	}
	return nil
}

// Response for updating performance metrics for a specific content format
type UpdateFormatPerformanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFormatPerformanceResponse) Reset() {
	*x = UpdateFormatPerformanceResponse{}
	mi := &file_content_pb_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormatPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormatPerformanceResponse) ProtoMessage() {}

func (x *UpdateFormatPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormatPerformanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateFormatPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateFormatPerformanceResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

// Request for getting all scheduled posts
type GetScheduledPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledPostsRequest) Reset() {
	*x = GetScheduledPostsRequest{}
	mi := &file_content_pb_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledPostsRequest) ProtoMessage() {}

func (x *GetScheduledPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledPostsRequest.ProtoReflect.Descriptor instead.
func (*GetScheduledPostsRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{14}
}

func (x *GetScheduledPostsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// Response for getting all scheduled posts
type GetScheduledPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*ScheduledPost       `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledPostsResponse) Reset() {
	*x = GetScheduledPostsResponse{}
	mi := &file_content_pb_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledPostsResponse) ProtoMessage() {}

func (x *GetScheduledPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledPostsResponse.ProtoReflect.Descriptor instead.
func (*GetScheduledPostsResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{15}
}

func (x *GetScheduledPostsResponse) GetPosts() []*ScheduledPost {
	if x != nil {
		return x.Posts
	}
	return nil
}

// Request for getting a specific scheduled post
type GetScheduledPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledPostRequest) Reset() {
	*x = GetScheduledPostRequest{}
	mi := &file_content_pb_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledPostRequest) ProtoMessage() {}

func (x *GetScheduledPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledPostRequest.ProtoReflect.Descriptor instead.
func (*GetScheduledPostRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{16}
}

func (x *GetScheduledPostRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetScheduledPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// Response for getting a specific scheduled post
type GetScheduledPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *ScheduledPost         `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledPostResponse) Reset() {
	*x = GetScheduledPostResponse{}
	mi := &file_content_pb_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledPostResponse) ProtoMessage() {}

func (x *GetScheduledPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledPostResponse.ProtoReflect.Descriptor instead.
func (*GetScheduledPostResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{17}
}

func (x *GetScheduledPostResponse) GetPost() *ScheduledPost {
	if x != nil {
		return x.Post
	}
	return nil
}

// Request for scheduling a new post
type SchedulePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	ScheduledTime string                 `protobuf:"bytes,5,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"` // RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulePostRequest) Reset() {
	*x = SchedulePostRequest{}
	mi := &file_content_pb_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulePostRequest) ProtoMessage() {}

func (x *SchedulePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulePostRequest.ProtoReflect.Descriptor instead.
func (*SchedulePostRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{18}
}

func (x *SchedulePostRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SchedulePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SchedulePostRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SchedulePostRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SchedulePostRequest) GetScheduledTime() string {
	if x != nil {
		return x.ScheduledTime
	}
	return ""
}

// Response for scheduling a new post
type SchedulePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *ScheduledPost         `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulePostResponse) Reset() {
	*x = SchedulePostResponse{}
	mi := &file_content_pb_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulePostResponse) ProtoMessage() {}

func (x *SchedulePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulePostResponse.ProtoReflect.Descriptor instead.
func (*SchedulePostResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{19}
}

func (x *SchedulePostResponse) GetPost() *ScheduledPost {
	if x != nil {
		return x.Post
	}
	return nil
}

// Request for updating an existing scheduled post
type UpdateScheduledPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ScheduledTime string                 `protobuf:"bytes,7,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"` // RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduledPostRequest) Reset() {
	*x = UpdateScheduledPostRequest{}
	mi := &file_content_pb_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduledPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduledPostRequest) ProtoMessage() {}

func (x *UpdateScheduledPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduledPostRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduledPostRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateScheduledPostRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateScheduledPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdateScheduledPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateScheduledPostRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpdateScheduledPostRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *UpdateScheduledPostRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateScheduledPostRequest) GetScheduledTime() string {
	if x != nil {
		return x.ScheduledTime
	}
	return ""
}

// Response for updating an existing scheduled post
type UpdateScheduledPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *ScheduledPost         `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduledPostResponse) Reset() {
	*x = UpdateScheduledPostResponse{}
	mi := &file_content_pb_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduledPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduledPostResponse) ProtoMessage() {}

func (x *UpdateScheduledPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduledPostResponse.ProtoReflect.Descriptor instead.
func (*UpdateScheduledPostResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateScheduledPostResponse) GetPost() *ScheduledPost {
	if x != nil {
		return x.Post
	}
	return nil
}

// Request for deleting a scheduled post
type DeleteScheduledPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduledPostRequest) Reset() {
	*x = DeleteScheduledPostRequest{}
	mi := &file_content_pb_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduledPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduledPostRequest) ProtoMessage() {}

func (x *DeleteScheduledPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduledPostRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduledPostRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteScheduledPostRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteScheduledPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// Response for deleting a scheduled post
type DeleteScheduledPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduledPostResponse) Reset() {
	*x = DeleteScheduledPostResponse{}
	mi := &file_content_pb_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduledPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduledPostResponse) ProtoMessage() {}

func (x *DeleteScheduledPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduledPostResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduledPostResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteScheduledPostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request for getting all posts due for publishing
type GetPostsDueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Before        string                 `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"` // RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsDueRequest) Reset() {
	*x = GetPostsDueRequest{}
	mi := &file_content_pb_content_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsDueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsDueRequest) ProtoMessage() {}

func (x *GetPostsDueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsDueRequest.ProtoReflect.Descriptor instead.
func (*GetPostsDueRequest) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{24}
}

func (x *GetPostsDueRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetPostsDueRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

// Response for getting all posts due for publishing
type GetPostsDueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*ScheduledPost       `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsDueResponse) Reset() {
	*x = GetPostsDueResponse{}
	mi := &file_content_pb_content_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsDueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsDueResponse) ProtoMessage() {}

func (x *GetPostsDueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsDueResponse.ProtoReflect.Descriptor instead.
func (*GetPostsDueResponse) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{25}
}

func (x *GetPostsDueResponse) GetPosts() []*ScheduledPost {
	if x != nil {
		return x.Posts
	}
	return nil
}

// ContentFormat represents a content format entity
type ContentFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 format
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentFormat) Reset() {
	*x = ContentFormat{}
	mi := &file_content_pb_content_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentFormat) ProtoMessage() {}

func (x *ContentFormat) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentFormat.ProtoReflect.Descriptor instead.
func (*ContentFormat) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{26}
}

func (x *ContentFormat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentFormat) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ContentFormat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContentFormat) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ContentFormat) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ContentFormat) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// FormatPerformance represents performance metrics for a content format
type FormatPerformance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FormatId        string                 `protobuf:"bytes,2,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	EngagementRate  float64                `protobuf:"fixed64,3,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"`
	ReachRate       float64                `protobuf:"fixed64,4,opt,name=reach_rate,json=reachRate,proto3" json:"reach_rate,omitempty"`
	ConversionRate  float64                `protobuf:"fixed64,5,opt,name=conversion_rate,json=conversionRate,proto3" json:"conversion_rate,omitempty"`
	AudienceType    string                 `protobuf:"bytes,6,opt,name=audience_type,json=audienceType,proto3" json:"audience_type,omitempty"`
	MeasurementDate string                 `protobuf:"bytes,7,opt,name=measurement_date,json=measurementDate,proto3" json:"measurement_date,omitempty"` // RFC3339 format
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FormatPerformance) Reset() {
	*x = FormatPerformance{}
	mi := &file_content_pb_content_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatPerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatPerformance) ProtoMessage() {}

func (x *FormatPerformance) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatPerformance.ProtoReflect.Descriptor instead.
func (*FormatPerformance) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{27}
}

func (x *FormatPerformance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FormatPerformance) GetFormatId() string {
	if x != nil {
		return x.FormatId
	}
	return ""
}

func (x *FormatPerformance) GetEngagementRate() float64 {
	if x != nil {
		return x.EngagementRate
	}
	return 0
}

func (x *FormatPerformance) GetReachRate() float64 {
	if x != nil {
		return x.ReachRate
	}
	return 0
}

func (x *FormatPerformance) GetConversionRate() float64 {
	if x != nil {
		return x.ConversionRate
	}
	return 0
}

func (x *FormatPerformance) GetAudienceType() string {
	if x != nil {
		return x.AudienceType
	}
	return ""
}

func (x *FormatPerformance) GetMeasurementDate() string {
	if x != nil {
		return x.MeasurementDate
	}
	return ""
}

// ScheduledPost represents a scheduled post entity
type ScheduledPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ScheduledTime string                 `protobuf:"bytes,4,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"` // RFC3339 format
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                        // Pending, Published, Failed, Cancelled
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 format
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledPost) Reset() {
	*x = ScheduledPost{}
	mi := &file_content_pb_content_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledPost) ProtoMessage() {}

func (x *ScheduledPost) ProtoReflect() protoreflect.Message {
	mi := &file_content_pb_content_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledPost.ProtoReflect.Descriptor instead.
func (*ScheduledPost) Descriptor() ([]byte, []int) {
	return file_content_pb_content_proto_rawDescGZIP(), []int{28}
}

func (x *ScheduledPost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduledPost) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScheduledPost) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ScheduledPost) GetScheduledTime() string {
	if x != nil {
		return x.ScheduledTime
	}
	return ""
}

func (x *ScheduledPost) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ScheduledPost) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScheduledPost) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScheduledPost) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ScheduledPost) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_content_pb_content_proto protoreflect.FileDescriptor

const file_content_pb_content_proto_rawDesc = "" +
	"\n" +
	"\x18content/pb/content.proto\x12\acontent\"7\n" +
	"\x18GetContentFormatsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"M\n" +
	"\x19GetContentFormatsResponse\x120\n" +
	"\aformats\x18\x01 \x03(\v2\x16.content.ContentFormatR\aformats\"S\n" +
	"\x17GetContentFormatRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tformat_id\x18\x02 \x01(\tR\bformatId\"J\n" +
	"\x18GetContentFormatResponse\x12.\n" +
	"\x06format\x18\x01 \x01(\v2\x16.content.ContentFormatR\x06format\"o\n" +
	"\x1aCreateContentFormatRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"M\n" +
	"\x1bCreateContentFormatResponse\x12.\n" +
	"\x06format\x18\x01 \x01(\v2\x16.content.ContentFormatR\x06format\"\x8c\x01\n" +
	"\x1aUpdateContentFormatRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tformat_id\x18\x02 \x01(\tR\bformatId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"M\n" +
	"\x1bUpdateContentFormatResponse\x12.\n" +
	"\x06format\x18\x01 \x01(\v2\x16.content.ContentFormatR\x06format\"V\n" +
	"\x1aDeleteContentFormatRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tformat_id\x18\x02 \x01(\tR\bformatId\"7\n" +
	"\x1bDeleteContentFormatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x91\x01\n" +
	"\x1bGetFormatPerformanceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tformat_id\x18\x02 \x01(\tR\bformatId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"\\\n" +
	"\x1cGetFormatPerformanceResponse\x12<\n" +
	"\vperformance\x18\x01 \x03(\v2\x1a.content.FormatPerformanceR\vperformance\"\x98\x01\n" +
	"\x1eUpdateFormatPerformanceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tformat_id\x18\x02 \x01(\tR\bformatId\x12<\n" +
	"\vperformance\x18\x03 \x03(\v2\x1a.content.FormatPerformanceR\vperformance\"F\n" +
	"\x1fUpdateFormatPerformanceResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\"7\n" +
	"\x18GetScheduledPostsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"I\n" +
	"\x19GetScheduledPostsResponse\x12,\n" +
	"\x05posts\x18\x01 \x03(\v2\x16.content.ScheduledPostR\x05posts\"O\n" +
	"\x17GetScheduledPostRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\"F\n" +
	"\x18GetScheduledPostResponse\x12*\n" +
	"\x04post\x18\x01 \x01(\v2\x16.content.ScheduledPostR\x04post\"\xa7\x01\n" +
	"\x13SchedulePostRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12%\n" +
	"\x0escheduled_time\x18\x05 \x01(\tR\rscheduledTime\"B\n" +
	"\x14SchedulePostResponse\x12*\n" +
	"\x04post\x18\x01 \x01(\v2\x16.content.ScheduledPostR\x04post\"\xdf\x01\n" +
	"\x1aUpdateScheduledPostRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0escheduled_time\x18\a \x01(\tR\rscheduledTime\"I\n" +
	"\x1bUpdateScheduledPostResponse\x12*\n" +
	"\x04post\x18\x01 \x01(\v2\x16.content.ScheduledPostR\x04post\"R\n" +
	"\x1aDeleteScheduledPostRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\"7\n" +
	"\x1bDeleteScheduledPostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x12GetPostsDueRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06before\x18\x02 \x01(\tR\x06before\"C\n" +
	"\x13GetPostsDueResponse\x12,\n" +
	"\x05posts\x18\x01 \x03(\v2\x16.content.ScheduledPostR\x05posts\"\xb0\x01\n" +
	"\rContentFormat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x81\x02\n" +
	"\x11FormatPerformance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tformat_id\x18\x02 \x01(\tR\bformatId\x12'\n" +
	"\x0fengagement_rate\x18\x03 \x01(\x01R\x0eengagementRate\x12\x1d\n" +
	"\n" +
	"reach_rate\x18\x04 \x01(\x01R\treachRate\x12'\n" +
	"\x0fconversion_rate\x18\x05 \x01(\x01R\x0econversionRate\x12#\n" +
	"\raudience_type\x18\x06 \x01(\tR\faudienceType\x12)\n" +
	"\x10measurement_date\x18\a \x01(\tR\x0fmeasurementDate\"\x87\x02\n" +
	"\rScheduledPost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12%\n" +
	"\x0escheduled_time\x18\x04 \x01(\tR\rscheduledTime\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt2\xce\t\n" +
	"\x0eContentService\x12Z\n" +
	"\x11GetContentFormats\x12!.content.GetContentFormatsRequest\x1a\".content.GetContentFormatsResponse\x12W\n" +
	"\x10GetContentFormat\x12 .content.GetContentFormatRequest\x1a!.content.GetContentFormatResponse\x12`\n" +
	"\x13CreateContentFormat\x12#.content.CreateContentFormatRequest\x1a$.content.CreateContentFormatResponse\x12`\n" +
	"\x13UpdateContentFormat\x12#.content.UpdateContentFormatRequest\x1a$.content.UpdateContentFormatResponse\x12`\n" +
	"\x13DeleteContentFormat\x12#.content.DeleteContentFormatRequest\x1a$.content.DeleteContentFormatResponse\x12c\n" +
	"\x14GetFormatPerformance\x12$.content.GetFormatPerformanceRequest\x1a%.content.GetFormatPerformanceResponse\x12l\n" +
	"\x17UpdateFormatPerformance\x12'.content.UpdateFormatPerformanceRequest\x1a(.content.UpdateFormatPerformanceResponse\x12Z\n" +
	"\x11GetScheduledPosts\x12!.content.GetScheduledPostsRequest\x1a\".content.GetScheduledPostsResponse\x12W\n" +
	"\x10GetScheduledPost\x12 .content.GetScheduledPostRequest\x1a!.content.GetScheduledPostResponse\x12K\n" +
	"\fSchedulePost\x12\x1c.content.SchedulePostRequest\x1a\x1d.content.SchedulePostResponse\x12`\n" +
	"\x13UpdateScheduledPost\x12#.content.UpdateScheduledPostRequest\x1a$.content.UpdateScheduledPostResponse\x12`\n" +
	"\x13DeleteScheduledPost\x12#.content.DeleteScheduledPostRequest\x1a$.content.DeleteScheduledPostResponse\x12H\n" +
	"\vGetPostsDue\x12\x1b.content.GetPostsDueRequest\x1a\x1c.content.GetPostsDueResponseB0Z.github.com/donaldnash/go-competitor/content/pbb\x06proto3"

var (
	file_content_pb_content_proto_rawDescOnce sync.Once
	file_content_pb_content_proto_rawDescData []byte
)

func file_content_pb_content_proto_rawDescGZIP() []byte {
	file_content_pb_content_proto_rawDescOnce.Do(func() {
		file_content_pb_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_pb_content_proto_rawDesc), len(file_content_pb_content_proto_rawDesc)))
	})
	return file_content_pb_content_proto_rawDescData
}

var file_content_pb_content_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_content_pb_content_proto_goTypes = []any{
	(*GetContentFormatsRequest)(nil),        // 0: content.GetContentFormatsRequest
	(*GetContentFormatsResponse)(nil),       // 1: content.GetContentFormatsResponse
	(*GetContentFormatRequest)(nil),         // 2: content.GetContentFormatRequest
	(*GetContentFormatResponse)(nil),        // 3: content.GetContentFormatResponse
	(*CreateContentFormatRequest)(nil),      // 4: content.CreateContentFormatRequest
	(*CreateContentFormatResponse)(nil),     // 5: content.CreateContentFormatResponse
	(*UpdateContentFormatRequest)(nil),      // 6: content.UpdateContentFormatRequest
	(*UpdateContentFormatResponse)(nil),     // 7: content.UpdateContentFormatResponse
	(*DeleteContentFormatRequest)(nil),      // 8: content.DeleteContentFormatRequest
	(*DeleteContentFormatResponse)(nil),     // 9: content.DeleteContentFormatResponse
	(*GetFormatPerformanceRequest)(nil),     // 10: content.GetFormatPerformanceRequest
	(*GetFormatPerformanceResponse)(nil),    // 11: content.GetFormatPerformanceResponse
	(*UpdateFormatPerformanceRequest)(nil),  // 12: content.UpdateFormatPerformanceRequest
	(*UpdateFormatPerformanceResponse)(nil), // 13: content.UpdateFormatPerformanceResponse
	(*GetScheduledPostsRequest)(nil),        // 14: content.GetScheduledPostsRequest
	(*GetScheduledPostsResponse)(nil),       // 15: content.GetScheduledPostsResponse
	(*GetScheduledPostRequest)(nil),         // 16: content.GetScheduledPostRequest
	(*GetScheduledPostResponse)(nil),        // 17: content.GetScheduledPostResponse
	(*SchedulePostRequest)(nil),             // 18: content.SchedulePostRequest
	(*SchedulePostResponse)(nil),            // 19: content.SchedulePostResponse
	(*UpdateScheduledPostRequest)(nil),      // 20: content.UpdateScheduledPostRequest
	(*UpdateScheduledPostResponse)(nil),     // 21: content.UpdateScheduledPostResponse
	(*DeleteScheduledPostRequest)(nil),      // 22: content.DeleteScheduledPostRequest
	(*DeleteScheduledPostResponse)(nil),     // 23: content.DeleteScheduledPostResponse
	(*GetPostsDueRequest)(nil),              // 24: content.GetPostsDueRequest
	(*GetPostsDueResponse)(nil),             // 25: content.GetPostsDueResponse
	(*ContentFormat)(nil),                   // 26: content.ContentFormat
	(*FormatPerformance)(nil),               // 27: content.FormatPerformance
	(*ScheduledPost)(nil),                   // 28: content.ScheduledPost
}
var file_content_pb_content_proto_depIdxs = []int32{
	26, // 0: content.GetContentFormatsResponse.formats:type_name -> content.ContentFormat
	26, // 1: content.GetContentFormatResponse.format:type_name -> content.ContentFormat
	26, // 2: content.CreateContentFormatResponse.format:type_name -> content.ContentFormat
	26, // 3: content.UpdateContentFormatResponse.format:type_name -> content.ContentFormat
	27, // 4: content.GetFormatPerformanceResponse.performance:type_name -> content.FormatPerformance
	27, // 5: content.UpdateFormatPerformanceRequest.performance:type_name -> content.FormatPerformance
	28, // 6: content.GetScheduledPostsResponse.posts:type_name -> content.ScheduledPost
	28, // 7: content.GetScheduledPostResponse.post:type_name -> content.ScheduledPost
	28, // 8: content.SchedulePostResponse.post:type_name -> content.ScheduledPost
	28, // 9: content.UpdateScheduledPostResponse.post:type_name -> content.ScheduledPost
	28, // 10: content.GetPostsDueResponse.posts:type_name -> content.ScheduledPost
	0,  // 11: content.ContentService.GetContentFormats:input_type -> content.GetContentFormatsRequest
	2,  // 12: content.ContentService.GetContentFormat:input_type -> content.GetContentFormatRequest
	4,  // 13: content.ContentService.CreateContentFormat:input_type -> content.CreateContentFormatRequest
	6,  // 14: content.ContentService.UpdateContentFormat:input_type -> content.UpdateContentFormatRequest
	8,  // 15: content.ContentService.DeleteContentFormat:input_type -> content.DeleteContentFormatRequest
	10, // 16: content.ContentService.GetFormatPerformance:input_type -> content.GetFormatPerformanceRequest
	12, // 17: content.ContentService.UpdateFormatPerformance:input_type -> content.UpdateFormatPerformanceRequest
	14, // 18: content.ContentService.GetScheduledPosts:input_type -> content.GetScheduledPostsRequest
	16, // 19: content.ContentService.GetScheduledPost:input_type -> content.GetScheduledPostRequest
	18, // 20: content.ContentService.SchedulePost:input_type -> content.SchedulePostRequest
	20, // 21: content.ContentService.UpdateScheduledPost:input_type -> content.UpdateScheduledPostRequest
	22, // 22: content.ContentService.DeleteScheduledPost:input_type -> content.DeleteScheduledPostRequest
	24, // 23: content.ContentService.GetPostsDue:input_type -> content.GetPostsDueRequest
	1,  // 24: content.ContentService.GetContentFormats:output_type -> content.GetContentFormatsResponse
	3,  // 25: content.ContentService.GetContentFormat:output_type -> content.GetContentFormatResponse
	5,  // 26: content.ContentService.CreateContentFormat:output_type -> content.CreateContentFormatResponse
	7,  // 27: content.ContentService.UpdateContentFormat:output_type -> content.UpdateContentFormatResponse
	9,  // 28: content.ContentService.DeleteContentFormat:output_type -> content.DeleteContentFormatResponse
	11, // 29: content.ContentService.GetFormatPerformance:output_type -> content.GetFormatPerformanceResponse
	13, // 30: content.ContentService.UpdateFormatPerformance:output_type -> content.UpdateFormatPerformanceResponse
	15, // 31: content.ContentService.GetScheduledPosts:output_type -> content.GetScheduledPostsResponse
	17, // 32: content.ContentService.GetScheduledPost:output_type -> content.GetScheduledPostResponse
	19, // 33: content.ContentService.SchedulePost:output_type -> content.SchedulePostResponse
	21, // 34: content.ContentService.UpdateScheduledPost:output_type -> content.UpdateScheduledPostResponse
	23, // 35: content.ContentService.DeleteScheduledPost:output_type -> content.DeleteScheduledPostResponse
	25, // 36: content.ContentService.GetPostsDue:output_type -> content.GetPostsDueResponse
	24, // [24:37] is the sub-list for method output_type
	11, // [11:24] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_content_pb_content_proto_init() }
func file_content_pb_content_proto_init() {
	if File_content_pb_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_pb_content_proto_rawDesc), len(file_content_pb_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_pb_content_proto_goTypes,
		DependencyIndexes: file_content_pb_content_proto_depIdxs,
		MessageInfos:      file_content_pb_content_proto_msgTypes,
	}.Build()
	File_content_pb_content_proto = out.File
	file_content_pb_content_proto_goTypes = nil
	file_content_pb_content_proto_depIdxs = nil
}
